require 'net/http'

rules=[['ADF Faces Bad Practices: unsecure Attribute', 'java', 'adf_faces_bad_practices_unsecure_attribute'],
       ['Castor Bad Practices: Query Mode Not Read-Only', 'java', 'castor_bad_practices_query_mode_not_read_only'],
       ['Castor Bad Practices: Unspecified Query Mode', 'java', 'castor_bad_practices_unspecified_query_mode'],
       ['Code Correctness: Call to System.gc()', 'java', 'code_correctness_call_to_system_gc'],
       ['Code Correctness: Class Does Not Implement equals', 'java', 'code_correctness_class_does_not_implement_equals'],
       ['Code Correctness: Erroneous finalize() Method', 'java', 'code_correctness_erroneous_finalize_method'],
       ['Code Correctness: Multiple Stream Commits', 'java', 'code_correctness_multiple_stream_commits'],
       ['Code Correctness: toString on Array', 'java', 'code_correctness_tostring_on_array'],
       ['Dangerous Field', 'java', 'dangerous_field'],
       ['Dangerous Method', 'java', 'dangerous_method'],
       ['Dangerous Type', 'java', 'dangerous_class_function'],
       ['EJB Bad Practices: Use of AWT/Swing', 'java', 'ejb_bad_practices_use_of_awt_swing'],
       ['EJB Bad Practices: Use of Class Loader', 'java', 'ejb_bad_practices_use_of_classloader'],
       ['EJB Bad Practices: Use of Sockets', 'java', 'ejb_bad_practices_use_of_sockets'],
       ['EJB Bad Practices: Use of Synchronization Primitives', 'java', 'ejb_bad_practices_use_of_synchronization_primitives'],
       ['EJB Bad Practices: Use of java.io', 'java', 'ejb_bad_practices_use_of_java_io'],
       ['File Disclosure: J2EE', 'java', 'file_disclosure_j2ee'],
       ['File Disclosure: Spring', 'java', 'file_disclosure_spring'],
       ['File Disclosure: Spring Webflow', 'java', 'file_disclosure_spring_webflow'],
       ['File Disclosure: Struts', 'java', 'file_disclosure_struts'],
       ['Immutable Classes: Field Mutation', 'java', 'immutable_field_mutation'],
       ['Immutable Classes: Non-final Fields', 'java', 'immutable_non_final_fields'],
       ['Immutable Classes: Public Mutable Fields', 'java', 'immutable_public_mutable_fields'],
       ['J2EE Bad Practices: Sockets', 'java', 'j2ee_badpractices_sockets'],
       ['J2EE Bad Practices: getConnection()', 'java', 'j2ee_badpractices_getconnection'],
       ['Missing Check against Null', 'java', 'missing_check_against_null'],
       ['Missing Check for Null Parameter', 'java', 'missing_check_for_null_parameter'],
       ['Object Model Violation: Erroneous clone() Method', 'java', 'object_model_violation_erroneous_clone_method'],
       ['Object Model Violation: Just one of equals() and hashCode() Defined', 'java', 'object_model_violation_just_one_of_equals_hashcode_defined'],
       ['Object Model Violation: Just one of restoreState() and saveState() Defined', 'java', 'object_model_violation_just_one_of_restoreState_saveState_defined'],
       ['Obsolete: Deprecated by ESAPI', 'java', 'obsolete_deprecated_by_esapi'],
       ['Often Misused: Authentication', 'java', 'often_misused_authentication'],
       ['Often Misused: Encoding', 'java', 'often_misued_encoding'],
       ['Often Misused: Spring Remote Service', 'java', 'often_misused_spring_remote_service'],
       ['Often Misused: Spring Web Service', 'java', 'often_misused_spring_web_service'],
       ['Password Management: Weak Redundancy', 'java', 'password_management_weak_redundancy'],
       ['Poor Style: Explicit Call to finalize()', 'java', 'poor_style_explicit_call_to_finalize'],
       ['Spring MVC Bad Practices: Request Parameters Bound into Persisted Objects', 'java', 'spring_mvc_bad_practices_request_parameters_bound_into_persisted_objects'],
       ['Unchecked Return Value', 'java', 'unchecked_return_value'],
       ['Android Bad Practices: Use of Released Camera Resource', 'java', 'android_bad_practices_use_of_released_camera_resource'],
       ['Android Bad Practices: Use of Released Media Resource', 'java', 'android_bad_practices_use_of_released_media_resource'],
       ['Android Bad Practices: Use of Released SQLite Resource', 'java', 'android_bad_practices_use_of_released_sqlite_resource'],
       ['Code Correctness: Call to Thread.run()', 'java', 'code_correctness_call_to_thread_run'],
       ['Code Correctness: Call to notify()', 'java', 'code_correctness_call_to_notify'],
       ['Code Correctness: Class Does Not Implement Cloneable', 'java', 'code_correctness_class_does_not_implement_cloneable'],
       ['Code Correctness: Erroneous Class Compare', 'java', 'code_correctness_erroneous_class_compare'],
       ['Code Correctness: Erroneous Negative Value', 'java', 'erroneous_negative_value_variable'],
       ['Code Correctness: Erroneous String Compare', 'java', 'code_correctness_erroneous_string_compare'],
       ['Code Correctness: Erroneous Zero Value', 'java', 'erroneous_zero_value_variable'],
       ['Code Correctness: Incorrect serialPersistentFields Modifier', 'java', 'code_correctness_incorrect_serialpersistentfields_modifier'],
       ['Code Correctness: Misspelled Method Name', 'java', 'code_correctness_misspelled_method_name'],
       ['Code Correctness: Non-Synchronized Method Overrides Synchronized Method', 'java', 'code_correctness_non_synchronized_method_overrides'],
       ['Code Correctness: Regular Expressions Denial of Service', 'java', 'denial_of_service_regex_evaluation'],
       ['Code Correctness: null Argument to equals()', 'java', 'code_correctness_null_argument_to_equals'],
       ['Dead Code: Empty Try Block', 'java', 'dead_code_empty_try_block'],
       ['Dead Code: Expression is Always false', 'java', 'dead_code_expression_is_always_false'],
       ['Dead Code: Expression is Always true', 'java', 'dead_code_expression_is_always_true'],
       ['Dead Code: Unused Field', 'java', 'dead_code_unused_field'],
       ['Dead Code: Unused Method', 'java', 'dead_code_unused_method'],
       ['Null Dereference', 'java', 'null_dereference_dereference_after_store'],
       ['Obsolete', 'java', 'obsolete'],
       ['Poor Style: Confusing Naming(class_and_member)', 'java', 'poor_style_confusing_naming_class_and_member'],
       ['Poor Style: Confusing Naming(member_and_method)', 'java', 'poor_style_confusing_naming_member_and_method'],
       ['Poor Style: Empty Synchronized Block', 'java', 'poor_style_empty_synchronized_block'],
       ['Poor Style: Identifier Contains Dollar Symbol ($)', 'java', 'poor_style_identifier_contains_dollar_symbol'],
       ['Poor Style: Redundant Initialization', 'java', 'poor_style_redundant_initialization'],
       ['Poor Style: Value Never Read', 'java', 'poor_style_value_never_read'],
       ['Portability Flaw: File Separator', 'java', 'portability_flaw_file_separator'],
       ['Redundant Null Check', 'java', 'null_dereference_check_after_dereference'],
       ['Unreleased Resource: Android Camera', 'java', 'unreleased_resource_android_camera'],
       ['Unreleased Resource: Android Media', 'java', 'unreleased_resource_android_media'],
       ['Unreleased Resource: Android SQLite Database', 'java', 'unreleased_resource_android_sqlite_database'],
       ['Unreleased Resource: Files', 'java', 'unreleased_resource_files'],
       ['Unreleased Resource: Sockets', 'java', 'unreleased_resource_sockets'],
       ['Unreleased Resource: Streams', 'java', 'unreleased_resource'],
       ['Unreleased Resource: Synchronization', 'java', 'unreleased_resource_synchronization'],
       ['ADF Bad Practices: Default url-invoke-disallowed Setting', 'java', 'adf_bad_practices_default_url_invoke_disallowed_setting'],
       ['Cross-Site Request Forgery', 'java', 'csrf'],
       ['HTML5: Overly Permissive CORS Policy', 'java', 'html5_overly_permissive_cors_policy'],
       ['Hidden Field', 'java', 'hidden_field'],
       ['Insecure Storage: Android External Storage', 'java', 'insecure_storage_android_external_storage'],
       ['J2EE Bad Practices: Leftover Debug Code', 'java', 'j2ee_badpractices_leftover_debug_code'],
       ['Script Hijacking: Ad Hoc Ajax', 'java', 'javascript_hijacking_ad_hoc_ajax'],
       ['Script Hijacking: Vulnerable Framework', 'java', 'javascript_hijacking_vulnerable_framework'],
       ['Poor Logging Practice: Logger Not Declared Static Final', 'java', 'poor_logging_practice_logger_is_not_declared_static_final'],
       ['Poor Logging Practice: Multiple Loggers', 'java', 'poor_logging_practice_multiple_loggers'],
       ['Poor Logging Practice: Use of a System Output Stream', 'java', 'poor_logging_practice_use_of_a_system_output_stream'],
       ['Poor Style: Non-final Public Static Field', 'java', 'poor_style_non-final_public_static_field'],
       ['System Information Leak', 'java', 'system_information_leak'],
       ['System Information Leak: Apache Axis', 'java', 'system_information_leak_apache_axis'],
       ['System Information Leak: Apache Axis 2', 'java', 'system_information_leak_apache_axis2'],
       ['System Information Leak: HTML Comment in JSP', 'java', 'system_information_leak_html_comment_in_jsp'],
       ['System Information Leak: Incomplete Servlet Error Handling', 'java', 'system_information_leak_incomplete_servlet_error_handling'],
       ['System Information Leak: Overly Broad SQL Logging', 'java', 'system_information_leak_overly_broad_sql_logging'],
       ['Trust Boundary Violation', 'java', 'trust_boundary_violation'],
       ['Unsafe Mobile Code: Access Violation', 'java', 'unsafe_mobile_code_access_violation'],
       ['Unsafe Mobile Code: Database Access', 'java', 'unsafe_mobile_code_database_access'],
       ['Unsafe Mobile Code: Inner Class', 'java', 'unsafe_mobile_code_inner_class'],
       ['Unsafe Mobile Code: Public finalize() Method', 'java', 'unsafe_mobile_code_public_finalize_method'],
       ['Unsafe Mobile Code: Unsafe Array Declaration', 'java', 'unsafe_mobile_code_unsafe_array_declaration'],
       ['Unsafe Mobile Code: Unsafe Public Field', 'java', 'unsafe_mobile_code_unsafe_public_field'],
       ['Axis 2 Misconfiguration: Debug Information', 'java', 'axis2_misconfiguration_debug_information'],
       ['Axis 2 Misconfiguration: Insecure Message Security', 'java', 'axis2_misconfiguration_insecure_message_security'],
       ['Axis 2 Misconfiguration: Insecure Transport Receiver', 'java', 'axis2_misconfiguration_insecure_transport_receiver'],
       ['Axis 2 Misconfiguration: Insecure Transport Sender', 'java', 'axis2_misconfiguration_insecure_transport_sender'],
       ['Axis 2 Service Provider Misconfiguration: Inbound WS-Security Not Enabled', 'java', 'axis2_service_provider_misconfiguration_inbound_ws-security_not_enabled'],
       ['Axis 2 Service Provider Misconfiguration: Missing Inbound Encryption', 'java', 'axis2_service_provider_misconfiguration_missing_inbound_encryption'],
       ['Axis 2 Service Provider Misconfiguration: Missing Inbound Signature', 'java', 'axis2_service_provider_misconfiguration_missing_inbound_signature'],
       ['Axis 2 Service Provider Misconfiguration: Missing Inbound Timestamp', 'java', 'axis2_service_provider_misconfiguration_missing_inbound_timestamp'],
       ['Axis 2 Service Provider Misconfiguration: Missing Outbound Encryption', 'java', 'axis2_service_provider_misconfiguration_missing_outbound_encryption'],
       ['Axis 2 Service Provider Misconfiguration: Missing Outbound Signature', 'java', 'axis2_service_provider_misconfiguration_missing_outbound_signature'],
       ['Axis 2 Service Provider Misconfiguration: Missing Outbound Timestamp', 'java', 'axis2_service_provider_misconfiguration_missing_outbound_timestamp'],
       ['Axis 2 Service Provider Misconfiguration: Outbound WS-Security Not Enabled', 'java', 'axis2_service_provider_misconfiguration_outbound_ws-security_not_enabled'],
       ['Axis 2 Service Provider Misconfiguration: Unsigned Inbound Timestamp', 'java', 'axis2_service_provider_misconfiguration_unsigned_inbound_timestamp'],
       ['Axis 2 Service Provider Misconfiguration: Unsigned Outbound Timestamp', 'java', 'axis2_service_provider_misconfiguration_unsigned_outbound_timestamp'],
       ['Axis 2 Service Provider Misconfiguration: WS-Security Not Enabled', 'java', 'axis2_service_provider_misconfiguration_ws-security_not_enabled'],
       ['Axis 2 Service Provider Misconfiguration: Weak Token', 'java', 'axis2_service_provider_misconfiguration_weak_token'],
       ['Axis 2 Service Requester Misconfiguration: Inbound WS-Security Not Enabled', 'java', 'axis2_service_requester_misconfiguration_inbound_ws-security_not_enabled'],
       ['Axis 2 Service Requester Misconfiguration: Missing Inbound Encryption', 'java', 'axis2_service_requester_misconfiguration_missing_inbound_encryption'],
       ['Axis 2 Service Requester Misconfiguration: Missing Inbound Signature', 'java', 'axis2_service_requester_misconfiguration_missing_inbound_signature'],
       ['Axis 2 Service Requester Misconfiguration: Missing Inbound Timestamp', 'java', 'axis2_service_requester_misconfiguration_missing_inbound_timestamp'],
       ['Axis 2 Service Requester Misconfiguration: Missing Outbound Encryption', 'java', 'axis2_service_requester_misconfiguration_missing_outbound_encryption'],
       ['Axis 2 Service Requester Misconfiguration: Missing Outbound Signature', 'java', 'axis2_service_requester_misconfiguration_missing_outbound_signature'],
       ['Axis 2 Service Requester Misconfiguration: Missing Outbound Timestamp', 'java', 'axis2_service_requester_misconfiguration_missing_outbound_timestamp'],
       ['Axis 2 Service Requester Misconfiguration: Outbound WS-Security Not Enabled', 'java', 'axis2_service_requester_misconfiguration_outbound_ws-security_not_enabled'],
       ['Axis 2 Service Requester Misconfiguration: Plain Text Password', 'java', 'axis2_service_requester_misconfiguration_plain_text_password'],
       ['Axis 2 Service Requester Misconfiguration: Unsigned Inbound Timestamp', 'java', 'axis2_service_requester_misconfiguration_unsigned_inbound_timestamp'],
       ['Axis 2 Service Requester Misconfiguration: Unsigned Outbound Timestamp', 'java', 'axis2_service_requester_misconfiguration_unsigned_outbound_timestamp'],
       ['Axis 2 Service Requester Misconfiguration: WS-Security Not Enabled', 'java', 'axis2_service_requester_misconfiguration_ws-security_not_enabled'],
       ['Axis 2 Service Requester Misconfiguration: Weak Token', 'java', 'axis2_service_requester_misconfiguration_weak_token'],
       ['Axis Misconfiguration: Debug Information', 'java', 'axis_misconfiguration_debug_information'],
       ['Axis Misconfiguration: Service Enumeration', 'java', 'axis_misconfiguration_service_enumeration'],
       ['Axis Service Provider Misconfiguration: Plain Text Password', 'java', 'axis_service_provider_misconfiguration_plain_text_password'],
       ['Axis Service Provider Misconfiguration: Weak Token', 'java', 'axis_service_provider_misconfiguration_weak_token'],
       ['Axis Service Requester Misconfiguration: Plain Text Password', 'java', 'axis_service_requester_misconfiguration_plain_text_password'],
       ['Axis Service Requester Misconfiguration: Weak Token', 'java', 'axis_service_requester_misconfiguration_weak_token'],
       ['Build Misconfiguration: Dynamic Dependency Version Usage', 'java', 'build_misconfiguration_dynamic_dependency_version'],
       ['Build Misconfiguration: External Ant Dependency Repository', 'java', 'build_misconfiguration_external_ant_dependency_repository'],
       ['Build Misconfiguration: External Ivy Dependency Repository', 'java', 'build_misconfiguration_external_ivy_dependency_repository'],
       ['Build Misconfiguration: External Maven Dependency Repository', 'java', 'build_misconfiguration_external_maven_dependency_repository'],
       ['Flex Misconfiguration: Debug Information', 'java', 'flex_misconfiguration_debug_information'],
       ['J2EE Misconfiguration: Cookies Disabled', 'java', 'j2ee_misconfiguration_cookies_disabled'],
       ['J2EE Misconfiguration: Debug Information', 'java', 'j2ee_misconfiguration_debug_information'],
       ['J2EE Misconfiguration: Direct JSP Access', 'java', 'j2ee_misconfiguration_direct_jsp_access'],
       ['J2EE Misconfiguration: Duplicate Security Role', 'java', 'j2ee_misconfiguration_duplicate_security_role'],
       ['J2EE Misconfiguration: Duplicate Servlet Mapping', 'java', 'j2ee_misconfiguration_duplicate_servlet_mapping'],
       ['J2EE Misconfiguration: Excessive Servlet Mappings', 'java', 'j2ee_misconfiguration_excessive_servlet_mappings'],
       ['J2EE Misconfiguration: Excessive Session Timeout', 'java', 'j2ee_misconfiguration_excessive_session_timeout'],
       ['J2EE Misconfiguration: Incomplete Error Handling - (404)', 'java', 'j2ee_misconfiguration_missing_error_handling_abs_404'],
       ['J2EE Misconfiguration: Incomplete Error Handling - (500)', 'java', 'j2ee_misconfiguration_missing_error_handling_abs_500'],
       ['J2EE Misconfiguration: Incomplete Error Handling - (throwable)', 'java', 'j2ee_misconfiguration_missing_error_handling_abs_throwable'],
       ['J2EE Misconfiguration: Insecure Transport', 'java', 'j2ee_misconfiguration_insecure_transport'],
       ['J2EE Misconfiguration: Insufficient Session-ID Length', 'java', 'j2ee_misconfiguration_insufficient_session_id_length'],
       ['J2EE Misconfiguration: Invalid Servlet Name', 'java', 'j2ee_misconfiguration_invalid_servlet_name'],
       ['J2EE Misconfiguration: Missing Authentication Method', 'java', 'j2ee_misconfiguration_missing_authentication_method'],
       ['J2EE Misconfiguration: Missing Data Transport Constraint', 'java', 'j2ee_misconfiguration_missing_data_transport_constraint'],
       ['J2EE Misconfiguration: Missing Error Handling', 'java', 'j2ee_misconfiguration_missing_error_handling'],
       ['J2EE Misconfiguration: Missing Filter Definition', 'java', 'j2ee_misconfiguration_missing_filter_definition'],
       ['J2EE Misconfiguration: Missing Security Role', 'java', 'j2ee_misconfiguration_missing_security_role'],
       ['J2EE Misconfiguration: Missing Servlet Mapping', 'java', 'j2ee_misconfiguration_missing_servlet_mapping'],
       ['J2EE Misconfiguration: Unsafe Bean Declaration', 'java', 'j2ee_misconfiguration_unsafe_bean_declaration'],
       ['J2EE Misconfiguration: Weak Access Permissions', 'java', 'j2ee_misconfiguration_weak_access_permissions'],
       ['Password Management: Empty Password in Configuration File', 'java', 'password_management_empty_password_in_configuration_file'],
       ['Password Management: Password in Configuration File', 'java', 'password_management_password_in_configuration_file'],
       ['Struts Misconfiguration: Duplicate Form Bean', 'java', 'struts_misconfiguration_duplicate_form_bean'],
       ['Struts Misconfiguration: Invalid Path', 'java', 'struts_misconfiguration_invalid_path'],
       ['Struts Misconfiguration: Missing Action Input', 'java', 'struts_misconfiguration_missing_action_input'],
       ['Struts Misconfiguration: Missing Exception Type', 'java', 'struts_misconfiguration_missing_exception_type'],
       ['Struts Misconfiguration: Missing Form Bean', 'java', 'struts_misconfiguration_missing_form_bean'],
       ['Struts Misconfiguration: Missing Form Bean Name', 'java', 'struts_misconfiguration_missing_form_bean_name'],
       ['Struts Misconfiguration: Missing Form Bean Type', 'java', 'struts_misconfiguration_missing_form_bean_type'],
       ['Struts Misconfiguration: Missing Form Property Type', 'java', 'struts_misconfiguration_missing_form_property_type'],
       ['Struts Misconfiguration: Missing Forward Name', 'java', 'struts_misconfiguration_missing_forward_name'],
       ['Struts Misconfiguration: Missing Forward Path', 'java', 'struts_misconfiguration_missing_forward_path'],
       ['Tomcat Configuration: Insecure Transport', 'java', 'tomcat_configuration_insecure_transport'],
       ['WebSphere Misconfiguration: Missing Nonce', 'java', 'websphere_misconfiguration_missing_nonce'],
       ['WebSphere Misconfiguration: Servlets Served By Class Name', 'java', 'websphere_misconfiguration_servlets_served_by_class_name'],
       ['WebSphere Service Provider Misconfiguration: Inbound WS-Security Not Enabled', 'java', 'websphere_service_provider_misconfiguration_inbound_ws-security_not_enabled'],
       ['WebSphere Service Provider Misconfiguration: Missing Inbound Encryption', 'java', 'websphere_service_provider_misconfiguration_missing_inbound_encryption'],
       ['WebSphere Service Provider Misconfiguration: Missing Inbound Signature', 'java', 'websphere_service_provider_misconfiguration_missing_inbound_signature'],
       ['WebSphere Service Provider Misconfiguration: Missing Inbound Timestamp', 'java', 'websphere_service_provider_misconfiguration_missing_inbound_timestamp'],
       ['WebSphere Service Provider Misconfiguration: Missing Outbound Encryption', 'java', 'websphere_service_provider_misconfiguration_missing_outbound_encryption'],
       ['WebSphere Service Provider Misconfiguration: Missing Outbound Signature', 'java', 'websphere_service_provider_misconfiguration_missing_outbound_signature'],
       ['WebSphere Service Provider Misconfiguration: Missing Outbound Timestamp', 'java', 'websphere_service_provider_misconfiguration_missing_outbound_timestamp'],
       ['WebSphere Service Provider Misconfiguration: Missing Timestamp Expiration', 'java', 'websphere_service_provider_misconfiguration_missing_timestamp_expiration'],
       ['WebSphere Service Provider Misconfiguration: Outbound WS-Security Not Enabled', 'java', 'websphere_service_provider_misconfiguration_outbound_ws-security_not_enabled'],
       ['WebSphere Service Provider Misconfiguration: Unsigned Inbound Timestamp', 'java', 'websphere_service_provider_misconfiguration_unsigned_inbound_timestamp'],
       ['WebSphere Service Provider Misconfiguration: Unsigned Outbound Timestamp', 'java', 'websphere_service_provider_misconfiguration_unsigned_outbound_timestamp'],
       ['WebSphere Service Provider Misconfiguration: Weak Token', 'java', 'websphere_service_provider_misconfiguration_weak_token'],
       ['WebSphere Service Requester Misconfiguration: Inbound WS-Security Not Enabled', 'java', 'websphere_service_requester_misconfiguration_inbound_ws-security_not_enabled'],
       ['WebSphere Service Requester Misconfiguration: Missing Inbound Encryption', 'java', 'websphere_service_requester_misconfiguration_missing_inbound_encryption'],
       ['WebSphere Service Requester Misconfiguration: Missing Inbound Signature', 'java', 'websphere_service_requester_misconfiguration_missing_inbound_signature'],
       ['WebSphere Service Requester Misconfiguration: Missing Inbound Timestamp', 'java', 'websphere_service_requester_misconfiguration_missing_inbound_timestamp'],
       ['WebSphere Service Requester Misconfiguration: Missing Outbound Encryption', 'java', 'websphere_service_requester_misconfiguration_missing_outbound_encryption'],
       ['WebSphere Service Requester Misconfiguration: Missing Outbound Signature', 'java', 'websphere_service_requester_misconfiguration_missing_outbound_signature'],
       ['WebSphere Service Requester Misconfiguration: Missing Outbound Timestamp', 'java', 'websphere_service_requester_misconfiguration_missing_outbound_timestamp'],
       ['WebSphere Service Requester Misconfiguration: Missing Timestamp Expiration', 'java', 'websphere_service_requester_misconfiguration_missing_timestamp_expiration'],
       ['WebSphere Service Requester Misconfiguration: Outbound WS-Security Not Enabled', 'java', 'websphere_service_requester_misconfiguration_outbound_ws-security_not_enabled'],
       ['WebSphere Service Requester Misconfiguration: Unsigned Inbound Timestamp', 'java', 'websphere_service_requester_misconfiguration_unsigned_inbound_timestamp'],
       ['WebSphere Service Requester Misconfiguration: Unsigned Outbound Timestamp', 'java', 'websphere_service_requester_misconfiguration_unsigned_outbound_timestamp'],
       ['WebSphere Service Requester Misconfiguration: Weak Token', 'java', 'websphere_service_requester_misconfiguration_weak_token'],
       ['Weblogic Misconfiguration: Missing Timestamp', 'java', 'weblogic_misconfiguration_missing_timestamp'],
       ['Weblogic Misconfiguration: Weak Token', 'java', 'weblogic_misconfiguration_weak_token'],
       ['Poor Error Handling: Empty Catch Block', 'java', 'poor_error_handling_empty_catch_block'],
       ['Poor Error Handling: Overly Broad Catch', 'java', 'poor_error_handling_overly_broad_catch'],
       ['Poor Error Handling: Overly Broad Throws', 'java', 'poor_error_handling_overly_broad_throws'],
       ['Poor Error Handling: Program Catches NullPointerException', 'java', 'poor_error_handling_program_catches_nullpointerexception'],
       ['Poor Error Handling: Return Inside Finally', 'java', 'poor_error_handling_return_inside_finally'],
       ['Poor Error Handling: Swallowed ThreadDeath', 'java', 'poor_error_handling_swallowed_threaddeath'],
       ['Poor Error Handling: Throw Inside Finally', 'java', 'poor_error_handling_throw_inside_finally'],
       ['Poor Error Handling: Unhandled SSL Exception', 'java', 'poor_error_handling_unhandled_ssl_exception'],
       ['ADF Bad Practices: Missing URL Parameter Converter', 'java', 'adf_bad_practices_missing_url_parameter_converter'],
       ['Command Injection', 'java', 'command_injection'],
       ['Cross-Site Scripting: DOM', 'java', 'cross_site_scripting_dom'],
       ['Cross-Site Scripting: External Links', 'java', 'xss_external_links'],
       ['Cross-Site Scripting: Persistent', 'java', 'cross_site_scripting_persistent'],
       ['Cross-Site Scripting: Poor Validation', 'java', 'cross_site_scripting_poor_validation'],
       ['Cross-Site Scripting: Reflected', 'java', 'cross_site_scripting_reflected'],
       ['Dangerous File Inclusion', 'java', 'dangerous_file_inclusion'],
       ['Denial of Service', 'java', 'denial_of_service'],
       ['Denial of Service: Parse Double', 'java', 'denial_of_service_parse_double'],
       ['Dynamic Code Evaluation: Code Injection', 'java', 'dynamic_code_evaluation_code_injection'],
       ['Header Manipulation', 'java', 'header_manipulation'],
       ['Header Manipulation: Cookies', 'java', 'header_manipulation'],
       ['LDAP Injection', 'java', 'ldap_injection'],
       ['LDAP Manipulation', 'java', 'ldap_manipulation'],
       ['Log Forging', 'java', 'log_forging'],
       ['Missing XML Validation', 'java', 'missing_xml_validation'],
       ['Often Misused: File Upload', 'java', 'often_misused_file_upload'],
       ['Open Redirect', 'java', 'open_redirect'],
       ['Path Manipulation', 'java', 'path_manipulation'],
       ['Process Control', 'java', 'process_control'],
       ['Process Control: Invoker Servlet', 'java', 'process_control_invoker_servlet'],
       ['Query String Injection: Amazon Web Services', 'java', 'query_string_injection_amazon_web_services'],
       ['Query String Injection: Android Provider', 'java', 'query_string_injection_android_provider'],
       ['Resource Injection', 'java', 'resource_injection'],
       ['SQL Injection', 'java', 'sql_injection'],
       ['SQL Injection: Hibernate', 'java', 'sql_injection_hibernate'],
       ['SQL Injection: JDO', 'java', 'sql_injection_jdo'],
       ['SQL Injection: Persistence', 'java', 'sql_injection_persistence'],
       ['SQL Injection: iBatis Data Map', 'java', 'sql_injection_ibatis_data_map'],
       ['Setting Manipulation', 'java', 'setting_manipulation'],
       ['Struts 2: Action Field Without Validator', 'java', 'struts2_action_field_without_validator'],
       ['Struts 2: Duplicate Action Field Validators', 'java', 'struts2_duplicate_action_field_validators'],
       ['Struts 2: Duplicate Validation Files', 'java', 'struts2_duplicate_validation_files'],
       ['Struts 2: Duplicate Validators', 'java', 'struts2_duplicate_validators'],
       ['Struts 2: Undeclared Validator', 'java', 'struts2_undeclared_validator'],
       ['Struts 2: Unvalidated Action', 'java', 'struts2_unvalidated_action'],
       ['Struts 2: Validation File Without Action', 'java', 'struts2_validation_file_without_action'],
       ['Struts 2: Validator Without Action Field', 'java', 'struts2_validator_without_action_field'],
       ['Struts: Duplicate Validation Forms', 'java', 'struts_duplicate_validate_forms'],
       ['Struts: Erroneous validate() Method', 'java', 'struts_erroneous_validate_method'],
       ['Struts: Form Does Not Extend Validation Class', 'java', 'struts_form_does_not_extend_validation_class'],
       ['Struts: Form Field Without Validator', 'java', 'struts_form_field_without_validator'],
       ['Struts: Plugin Framework Not In Use', 'java', 'struts_plugin_framework_not_in_use'],
       ['Struts: Unused Action Form', 'java', 'struts_unused_action_form'],
       ['Struts: Unused Validation Form', 'java', 'struts_unused_validation_form'],
       ['Struts: Unvalidated Action Form', 'java', 'struts_unvalidated_action_form'],
       ['Struts: Validator Turned Off', 'java', 'struts_validator_turned_off'],
       ['Struts: Validator Without Form Field', 'java', 'struts_validator_without_form_field'],
       ['Unsafe JNI', 'java', 'unsafe_jni'],
       ['Unsafe Reflection', 'java', 'unsafe_reflection'],
       ['XML Injection', 'java', 'xml_injection'],
       ['XPath Injection', 'java', 'xpath_injection'],
       ['Access Control: Amazon Web Services', 'java', 'access_control_amazon_web_services'],
       ['Access Control: Android Provider', 'java', 'access_control_android_provider'],
       ['Access Control: Anonymous LDAP Bind', 'java', 'access_control_anonymous_ldap_bind'],
       ['Access Control: Database', 'java', 'access_control_database'],
       ['Access Control: LDAP', 'java', 'access_control_ldap'],
       ['Access Control: Weak Security Constraint', 'java', 'access_control_weak_security_constraint'],
       ['Acegi Misconfiguration: Insecure Channel Mixing', 'java', 'acegi_misconfiguration_insecure_channel_mixing'],
       ['Acegi Misconfiguration: Run-As Authentication Replacement', 'java', 'acegi_misconfiguration_run_as_authentication_replacement'],
       ['Android Bad Practices: Just Provider writePermission Defined', 'java', 'android_bad_practices_just_provider_writepermission_defined'],
       ['Android Bad Practices: Missing Broadcaster Permission', 'java', 'android_bad_practices_missing_broadcaster_permission'],
       ['Android Bad Practices: Missing Component Permission', 'java', 'android_bad_practices_missing_component_permission'],
       ['Android Bad Practices: Missing Receiver Permission', 'java', 'android_bad_practices_missing_receiver_permission'],
       ['Android Bad Practices: Missing exported Attribute', 'java', 'android_bad_practices_missing_exported_attribute'],
       ['Android Bad Practices: Provider permission Defined', 'java', 'android_bad_practices_provider_permission_defined'],
       ['Android Bad Practices: Sticky Broadcast', 'java', 'android_bad_practices_sticky_broadcast'],
       ['Android Bad Practices: normal Permission', 'java', 'android_bad_practices_normal_permission'],
       ['Cookie Security: Cookie not Sent Over SSL', 'java', 'cookie_security_cookie_not_sent_over_ssl'],
       ['Cookie Security: Overly Broad Domain', 'java', 'cookie_security_overly_broad_domain'],
       ['Cookie Security: Overly Broad Path', 'java', 'cookie_security_overly_broad_path'],
       ['Cookie Security: Persistent Cookie', 'java', 'cookie_security_persistent_cookie'],
       ['HTTP Verb Tampering', 'java', 'http_verb_tampering'],
       ['Insecure Randomness', 'java', 'insecure_randomness'],
       ['Missing SecurityManager Check: Cloneable', 'java', 'missing_securitymanager_check_cloneable'],
       ['Missing SecurityManager Check: Serializable', 'java', 'missing_securitymanager_check_serializable'],
       ['Password Management', 'java', 'password_management'],
       ['Password Management: Empty Password', 'java', 'password_management_empty_password'],
       ['Password Management: Hardcoded Password', 'java', 'password_management_hardcoded_password'],
       ['Password Management: Heap Inspection', 'java', 'password_management_heap_inspection'],
       ['Password Management: Null Password', 'java', 'password_management_null_password'],
       ['Password Management: Password in Comment', 'java', 'password_management_password_in_comment'],
       ['Password Management: Password in Redirect', 'java', 'password_management_redirect'],
       ['Password Management: Weak Cryptography', 'java', 'password_management_weak_cryptography'],
       ['Privacy Violation', 'java', 'privacy_violation'],
       ['Privacy Violation: Password', 'java', 'privacy_violation_password'],
       ['Privilege Management: Amazon Web Services Unchecked Permissions', 'java', 'privilege_management_amazon_web_services_unchecked_permissions'],
       ['Privilege Management: Android Data Storage', 'java', 'privilege_management_android_data_storage'],
       ['Privilege Management: Android Disable', 'java', 'privilege_management_android_disable'],
       ['Privilege Management: Android Location', 'java', 'privilege_management_android_location'],
       ['Privilege Management: Android Messaging', 'java', 'privilege_management_android_messaging'],
       ['Privilege Management: Android Network', 'java', 'privilege_management_android_network'],
       ['Privilege Management: Android Telephony', 'java', 'privilege_management_android_telephony'],
       ['Privilege Management: Missing API Permission', 'java', 'privilege_management_missing_api_permission'],
       ['Privilege Management: Missing Content Provider Permission', 'java', 'privilege_management_missing_content_provider_permission'],
       ['Privilege Management: Missing Intent Permission', 'java', 'privilege_management_missing_intent_permission'],
       ['Privilege Management: Overly Broad Access Specifier', 'java', 'privilege_management_overly_broad_access_specifier'],
       ['Privilege Management: Unnecessary Permission', 'java', 'privilege_management_unnecessary_permission'],
       ['Weak Cryptographic Hash', 'java', 'weak_cryptographic_hash'],
       ['Weak Cryptographic Hash: Hardcoded Salt', 'java', 'weak_cryptographic_hash_hardcoded_salt'],
       ['Weak Encryption', 'java', 'weak_encryption'],
       ['Weak Encryption: Inadequate RSA Padding', 'java', 'weak_encryption_inadequate_rsa_padding'],
       ['Weak Encryption: Insufficient Key Size', 'java', 'weak_encryption_insufficient_key_size'],
       ['Weak SecurityManager Check: Overridable Method', 'java', 'weak_securitymanager_check_overridable_method'],
       ['Code Correctness: Call to sleep() in Lock', 'java', 'code_correctness_call_to_sleep_in_lock'],
       ['Code Correctness: Double-Checked Locking', 'java', 'code_correctness_double_checked_locking'],
       ['J2EE Bad Practices: Non-Serializable Object Stored in Session', 'java', 'j2ee_bad_practices_non_serializable_object_stored_in_session'],
       ['J2EE Bad Practices: System.exit', 'java', 'j2ee_badpractices_system_exit'],
       ['J2EE Bad Practices: Threads', 'java', 'j2ee_badpractices_threads'],
       ['Race Condition: Format Flaw', 'java', 'race_condition_format_flaw'],
       ['Race Condition: Singleton Member Field', 'java', 'singleton_member_field_race_condition'],
       ['Race Condition: Static Database Connection(dbconn)', 'java', 'race_dbconn'],
       ['Session Fixation', 'java', 'session_fixation']]

puts "##############################################################"
puts "Generating src/main/resources/org/sonar/plugins/fortify/base/rules-java.xml"
puts "##############################################################"
open("src/main/resources/org/sonar/plugins/fortify/base/rules-java.xml", "w") do |file|
  file.write('<rules>
      <!-- see names and descriptions in org/sonar/l10n/ -->
  ')
  rules.each do |rule|
    key = rule[2]
    language=rule[1]
    name=rule[0]
    if language=='java'
      file.write("
        <rule>
          <key>#{key}</key><priority>MAJOR</priority><configKey>#{name}</configKey>
        </rule>
      ")
    end
  end
  file.write('</rules>')
end


puts "##############################################################"
puts "Copy paste the following to org/sonar/l10n/fortify.properties. Be careful to keep fortify.* properties."
puts "##############################################################"

Net::HTTP.start("www.hpenterprisesecurity.com") do |http|
  rules.each do |rule|
    key = rule[2]
    language=rule[1]
    name=rule[0]
    puts "rule.fortify-#{language}.#{key}.name=#{name}"
    resp = http.get("/vulncat/en/vulncat/#{language}/#{key}.html")
    open("src/main/resources/org/sonar/l10n/fortify/rules/fortify-#{language}/#{key}.html", "w") do |file|
      file.write(resp.body.gsub(/.*theContentCenter">/m, '').gsub(/<div id="theFooter">.*/m, ''))
    end
  end
end

