require 'net/http'

rules=[
  ['SQL Bad Practices: Direct Update', 'abap', 'sql_bad_practices_direct_update'],
  ['System Field Overwrite', 'abap', 'system_field_overwrite'],
  ['Obsolete', 'abap', 'obsolete'],
  ['System Information Leak', 'abap', 'system_information_leak'],
  ['Command Injection', 'abap', 'command_injection'],
  ['Cross-Site Scripting: Persistent', 'abap', 'cross_site_scripting_persistent'],
  ['Cross-Site Scripting: Poor Validation', 'abap', 'cross_site_scripting_poor_validation'],
  ['Cross-Site Scripting: Reflected', 'abap', 'cross_site_scripting_reflected'],
  ['Denial of Service', 'abap', 'denial_of_service'],
  ['Dynamic Code Evaluation: Code Injection', 'abap', 'dynamic_code_evaluation_code_injection'],
  ['Header Manipulation', 'abap',  'header_manipulation'],
  ['Header Manipulation: Cookies', 'abap', 'header_manipulation_cookies'],
  ['Log Forging', 'abap', 'log_forging'],
  ['Open Redirect', 'abap', 'open_redirect'],
  ['Path Manipulation', 'abap', 'path_manipulation'],
  ['Process Control', 'abap', 'process_control'],
  ['Resource Injection', 'abap', 'resource_injection'],
  ['SQL Injection', 'abap', 'sql_injection'],
  ['Security Features', 'abap', 'SF'],
  ['Access Control: Database', 'abap', 'access_control_database'],
  ['Access Control: Missing Authorization Check', 'abap', 'access_control_missing_authorization_check'],
  ['Password Management: Empty Password', 'abap', 'password_management_empty_password'],
  ['Password Management: Hardcoded Password', 'abap', 'password_management_hardcoded_password'],
  ['Password Management: Password in Comment', 'abap', 'password_management_password_in_comment'],
  ['Privacy Violation', 'abap', 'privacy_violation'],
  ['System Information Leak', 'cobol', 'system_information_leak'],
  ['Poor Condition Handling: Ignored Condition', 'cobol', 'poor_condition_handling_ignored_condition'],
  ['Cross-Site Scripting: Persistent', 'cobol', 'cross_site_scripting_persistent'],
  ['Cross-Site Scripting: Reflected', 'cobol', 'cross_site_scripting_reflected'],
  ['Header Manipulation', 'cobol', 'header_manipulation'],
  ['Log Forging', 'cobol', 'log_forging'],
  ['Path Manipulation', 'cobol', 'path_manipulation'],
  ['Process Control', 'cobol', 'process_control'],
  ['Resource Injection', 'cobol', 'resource_injection'],
  ['SQL Injection', 'cobol', 'sql_injection'],
  ['Setting Manipulation', 'cobol', 'setting_manipulation'],
  ['Security Features', 'cobol', 'SF'],
  ['Access Control: DLI', 'cobol', 'access_control_dli'],
  ['Access Control: Database', 'cobol', 'access_control_database'],
  ['Access Control: MQ', 'cobol', 'access_control_mq'],
  ['Password Management', 'cobol', 'password_management'],
  ['Password Management: Hardcoded Password', 'cobol', 'password_management_hardcoded_password'],
  ['Password Management: Password in Comment', 'cobol', 'password_management_password_in_comment'],
  ['Password Management: Weak Cryptography', 'cobol', 'password_management_weak_cryptography'],
  ['Privacy Violation', 'cobol', 'privacy_violation'],
  ['Dangerous Function', 'cpp', 'dangerous_function_master'],
  ['Directory Restriction', 'cpp', 'directory_restriction'],
  ['Heap Inspection', 'cpp', 'heap_inspection'],
  ['Heap Inspection: Swappable Memory', 'cpp', 'heap_inspection_swappable_memory'],
  ['Missing Check against Null', 'cpp', 'missing_check_against_null'],
  ['Often Misused: Authentication(gethostby)', 'cpp', 'often_misused_authentication_gethostby'],
  ['Often Misused: Authentication(getlogin)', 'cpp', 'often_misused_authentication_getlogin'],
  ['Often Misused: Exception Handling(_alloca)', 'cpp', 'often_misused_exception_handling__alloca'],
  ['Often Misused: Exception Handling(criticalsection)', 'cpp', 'often_misused_exception_handling_criticalsection'],
  ['Often Misused: File System(getwd)', 'cpp', 'often_misused_file_system_getwd'],
  ['Often Misused: File System(readlink)', 'cpp', 'often_misused_file_system_readlink'],
  ['Often Misused: File System(realpath)', 'cpp', 'often_misused_file_system_realpath'],
  ['Often Misused: File System(umask)', 'cpp', 'often_misused_file_system_umask'],
  ['Often Misused: File System(windows)', 'cpp', 'often_misused_file_system_windows'],
  ['Often Misused: Privilege Management', 'cpp', 'often_misused_privilege_management'],
  ['Often Misused: Privilege Management(setuid)', 'cpp', 'often_misused_privilege_management_setuid'],
  ['Often Misused: Strings(_mbs)', 'cpp', 'often_misused_strings__mbs'],
  ['Often Misused: Strings(multibytewidechar)', 'cpp', 'often_misused_strings_multibytewidechar'],
  ['Unchecked Return Value', 'cpp', 'unchecked_return_value'],
  ['Code Correctness: Arithmetic Operation on Boolean', 'cpp', 'code_correctness_arithmetic_operation_on_boolean'],
  ['Code Correctness: Function Not Invoked', 'cpp', 'code_correctness_function_not_invoked'],
  ['Code Correctness: Function Returns Stack Address', 'cpp', 'code_correctness_function_returns_stack_address'],
  ['Code Correctness: Macro Misuse', 'cpp', 'code_correctness_macro_misuse'],
  ['Code Correctness: Memory Free on Stack Variable', 'cpp', 'code_correctness_memory_free_on_stack_variable'],
  ['Code Correctness: Premature Thread Termination', 'cpp', 'code_correctness_premature_thread_termination'],
  ['Dead Code', 'cpp', 'dead_code'],
  ['Double Free', 'cpp', 'double_free'],
  ['Format String: Argument Number Mismatch', 'cpp', 'format_string_argument_number_mismatch'],
  ['Format String: Argument Type Mismatch', 'cpp', 'format_string_argument_type_mismatch'],
  ['Memory Leak', 'cpp', 'memory_leak'],
  ['Memory Leak: Reallocation', 'cpp', 'memory_leak_reallocation'],
  ['Null Dereference', 'cpp', 'null_dereference_dereference_after_store'],
  ['Obsolete', 'cpp', 'obsolete'],
  ['Obsolete: Inadequate Pointer Validation', 'cpp', 'obsolete_inadequate_pointer_validation'],
  ['Poor Style: Redundant Initialization', 'cpp', 'poor_style_redundant_initialization'],
  ['Poor Style: Value Never Read', 'cpp', 'poor_style_value_never_read'],
  ['Poor Style: Variable Never Used', 'cpp', 'poor_style_variable_never_used'],
  ['Portability Flaw', 'cpp', 'portability_flaw'],
  ['Redundant Null Check', 'cpp', 'null_dereference_dereference_after_check'],
  ['Type Mismatch: Integer to Character', 'cpp', 'type_mismatch_integer_to_character'],
  ['Type Mismatch: Negative to Unsigned', 'cpp', 'type_mismatch_negative_to_unsigned'],
  ['Type Mismatch: Signed to Unsigned', 'cpp', 'type_mismatch_signed_to_unsigned'],
  ['Undefined Behavior', 'cpp', 'undefined_behavior'],
  ['Undefined Behavior: Redundant Delete', 'cpp', 'redundant_delete'],
  ['Uninitialized Variable', 'cpp', 'uninitialized_variable'],
  ['Unreleased Resource', 'cpp', 'unreleased_resource'],
  ['Unreleased Resource: Synchronization', 'cpp', 'unreleased_resource_synchronization'],
  ['Use After Free', 'cpp', 'use_after_free'],
  ['System Information Leak', 'cpp', 'system_information_leak'],
  ['Insecure Compiler Optimization', 'cpp', 'insecure_compiler_optimization'],
  ['Insecure Compiler Optimization: Pointer Arithmetic', 'cpp', 'insecure_compiler_optimization_pointer_arithmetic'],
  ['Buffer Overflow', 'cpp', 'buffer_overflow'],
  ['Buffer Overflow: Format String', 'cpp', 'buffer_overflow_format_string'],
  ['Buffer Overflow: Format String (%f/%F)', 'cpp', 'buffer_overflow_format_string__percentf__percentF'],
  ['Buffer Overflow: Off-by-One', 'cpp', 'buffer_overflow_off_by_one'],
  ['Buffer Overflow: Signed Comparison', 'cpp', 'buffer_overflow_signed_comparison'],
  ['Command Injection', 'cpp', 'command_injection'],
  ['Denial of Service', 'cpp', 'denial_of_service'],
  ['Format String', 'cpp', 'format_string'],
  ['Illegal Pointer Value', 'cpp', 'illegal_pointer_value_master'],
  ['Integer Overflow', 'cpp', 'integer_overflow'],
  ['LDAP Injection', 'cpp', 'ldap_injection'],
  ['LDAP Manipulation', 'cpp', 'ldap_manipulation'],
  ['Log Forging', 'cpp', 'log_forging'],
  ['Out-of-Bounds Read', 'cpp', 'out_of_bounds_read'],
  ['Out-of-Bounds Read: Off-by-One', 'cpp', 'out_of_bounds_read_off_by_one'],
  ['Out-of-Bounds Read: Signed Comparison', 'cpp', 'out_of_bounds_read_signed_comparison'],
  ['Path Manipulation', 'cpp', 'path_manipulation'],
  ['Process Control', 'cpp', 'process_control'],
  ['Resource Injection', 'cpp', 'resource_injection'],
  ['SQL Injection', 'cpp', 'sql_injection'],
  ['Setting Manipulation', 'cpp', 'setting_manipulation'],
  ['String Termination Error', 'cpp', 'string_termination_error_master'],
  ['String Termination Error(truncate)', 'cpp', 'string_termination_error_truncate'],
  ['Unsafe Reflection', 'cpp', 'unsafe_reflection'],
  ['Security Features', 'cpp', 'SF'],
  ['Access Control: Anonymous LDAP Bind', 'cpp', 'access_control_anonymous_ldap_bind'],
  ['Access Control: Database', 'cpp', 'access_control_database'],
  ['Access Control: LDAP', 'cpp', 'access_control_ldap'],
  ['Insecure Randomness', 'cpp', 'insecure_randomness'],
  ['Key Management: Hardcoded Encryption Key', 'cpp', 'hardcoded_encryption_key'],
  ['Least Privilege Violation', 'cpp', 'least_privilege_violation'],
  ['Password Management', 'cpp', 'password_management'],
  ['Password Management: Empty Password', 'cpp', 'password_management_empty_password'],
  ['Password Management: Hardcoded Password', 'cpp', 'password_management_hardcoded_password'],
  ['Password Management: Null Password', 'cpp', 'password_management_null_password'],
  ['Password Management: Password in Comment', 'cpp', 'password_management_password_in_comment'],
  ['Password Management: Weak Cryptography', 'cpp', 'password_management_weak_cryptography'],
  ['Privacy Violation', 'cpp', 'privacy_violation'],
  ['Weak Cryptographic Hash', 'cpp', 'weak_cryptographic_hash'],
  ['Weak Cryptographic Hash: Hardcoded Salt', 'cpp', 'weak_cryptographic_hash_hardcoded_salt'],
  ['Weak Encryption', 'cpp', 'weak_encryption'],
  ['Weak Encryption: Inadequate RSA Padding', 'cpp', 'weak_encryption_inadequate_rsa_padding'],
  ['Weak Encryption: Insufficient Key Size', 'cpp', 'weak_encryption_insufficient_key_size'],
  ['Code Correctness: Erroneous Synchronization', 'cpp', 'code_correctness_erroneous_synchronization'],
  ['Insecure Temporary File', 'cpp', 'insecure_temporary_file'],
  ['Race Condition: File System Access', 'cpp', 'file_access_race_condition'],
  ['Race Condition: Signal Handling', 'cpp', 'race_condition_signal_handling'],
  ['ASP.NET MVC Bad Practices: Request Parameters Bound into Persisted Objects', 'dotnet', 'dotnet_mvc_bad_practices_request_parameters_bound_into_persisted_objects'],
  ['Code Correctness: Call to GC.Collect()', 'dotnet', 'code_correctness_call_to_gc_collect'],
  ['Code Correctness: Class Does Not Implement Equals', 'dotnet', 'code_correctness_class_does_not_implement_equals'],
  ['Code Correctness: ToString on Array', 'dotnet', 'code_correctness_tostring_on_array'],
  ['Missing Check against Null', 'dotnet', 'missing_check_against_null'],
  ['Object Model Violation: Just One of Equals() and GetHashCode() Defined(just_one_of_equals_hashcode_defined)', 'dotnet', 'object_model_violation_just_one_of_equals_hashcode_defined'],
  ['Often Misused: Authentication', 'dotnet', 'often_misused_authentication'],
  ['Unchecked Return Value', 'dotnet', 'unchecked_return_value'],
  ['ASP.NET Bad Practices: Unminified Code', 'dotnet', 'asp_net_bad_practices_unminified_code'],
  ['Code Correctness: Class Implements ICloneable', 'dotnet', 'code_correctness_class_implements_icloneable'],
  ['Code Correctness: Erroneous Class Compare', 'dotnet', 'code_correctness_erroneous_class_compare'],
  ['Code Correctness: Missing [Serializable] Attribute', 'dotnet', 'code_correctness_missing_serializable_attribute'],
  ['Code Correctness: Misspelled Method Name', 'dotnet', 'code_correctness_misspelled_method_name'],
  ['Code Correctness: Regular Expressions Denial of Service', 'dotnet', 'denial_of_service_regex_evaluation'],
  ['Code Correctness: null Argument to Equals()', 'dotnet', 'code_correctness_null_argument_to_equals'],
  ['Dead Code: Unused Field', 'dotnet', 'dead_code_unused_field'],
  ['Dead Code: Unused Method', 'dotnet', 'dead_code_unused_method'],
  ['Null Dereference', 'dotnet', 'null_dereference'],
  ['Obsolete', 'dotnet', 'obsolete'],
  ['Portability Flaw: File Separator', 'dotnet', 'portability_flaw_file_separator'],
  ['Unreleased Resource: Database', 'dotnet', 'unreleased_resource'],
  ['Unreleased Resource: Synchronization', 'dotnet', 'unreleased_resource_synchronization'],
  ['Unreleased Resource: Unmanaged Object(unmanaged_object)', 'dotnet', 'unreleased_resource_unmanaged_object'],
  ['ASP.NET Bad Practices: Leftover Debug Code', 'dotnet', 'asp_dotnet_bad_practices_leftover_debug_code'],
  ['Cross-Site Request Forgery', 'dotnet', 'csrf'],
  ['HTML5: Overly Permissive CORS Policy', 'dotnet', 'html5_overly_permissive_cors_policy'],
  ['Hidden Field', 'dotnet', 'hidden_field'],
  ['JavaScript Hijacking: Vulnerable Framework', 'dotnet', 'javascript_hijacking_vulnerable_framework'],
  ['Poor Logging Practice: Use of a System Output Stream', 'dotnet', 'poor_logging_practice_use_of_a_system_output_stream'],
  ['System Information Leak', 'dotnet', 'system_information_leak'],
  ['Trust Boundary Violation', 'dotnet', 'trust_boundary_violation'],
  ['ASP.NET Misconfiguration: Certificate Validation Disabled', 'dotnet', 'asp_dotnet_misconfiguration_certificate_validation_disabled'],
  ['ASP.NET Misconfiguration: Cookie Protection Disabled', 'dotnet', 'asp_dotnet_misconfiguration_cookie_protection_disabled'],
  ['ASP.NET Misconfiguration: Debug Information', 'dotnet', 'asp_dotnet_misconfiguration_debug_info'],
  ['ASP.NET Misconfiguration: Excessive Session Timeout', 'dotnet', 'asp_dotnet_misconfiguration_excessive_session_timeout'],
  ['ASP.NET Misconfiguration: Incomplete Cookie Protection', 'dotnet', 'asp_dotnet_misconfiguration_incomplete_cookie_protection'],
  ['ASP.NET Misconfiguration: Incomplete Role Protection', 'dotnet', 'asp_dotnet_misconfiguration_incomplete_role_protection'],
  ['ASP.NET Misconfiguration: Password Protection Disabled', 'dotnet', 'asp_dotnet_misconfiguration_password_protection_disabled'],
  ['ASP.NET Misconfiguration: Request Validation Disabled', 'dotnet', 'asp_dotnet_misconfiguration_request_validation_disabled'],
  ['ASP.NET Misconfiguration: Request Validation Disabled(request_validation_disabled)', 'dotnet', 'asp_dotnet_misconfiguration_request_validation_disabled'],
  ['ASP.NET Misconfiguration: Role Protection Disabled', 'dotnet', 'asp_dotnet_misconfiguration_role_protection_disabled'],
  ['ASP.NET Misconfiguration: Session Cookies Disabled', 'dotnet', 'asp_net_misconfiguration_session_cookies_disabled'],
  ['ASP.NET Misconfiguration: Trace Output', 'dotnet', 'asp_dotnet_misconfiguration_trace_output'],
  ['ASP.NET Misconfiguration: Use of Impersonation Context', 'dotnet', 'asp_dotnet_misconfiguration_use_of_impersonation_context'],
  ['ASP.NET Misconfiguration: Weak Password Protection', 'dotnet', 'asp_dotnet_misconfiguration_weak_password_protection'],
  ['Cookie Security: HTTPOnly not Set on Application Cookie', 'dotnet', 'cookie_security_httponly_not_set_on_session_cookie'],
  ['Cookie Security: Session Cookie not Sent Over SSL', 'dotnet', 'cookie_security_session_cookie_not_sent_over_ssl'],
  ['External Content: Content Delivery Network', 'dotnet', 'external_content_content_delivery_network'],
  ['Password Management: Empty Password in Configuration File', 'dotnet', 'password_management_empty_password_in_configuration_file'],
  ['Password Management: Password in Configuration File', 'dotnet', 'password_management_password_in_configuration_file'],
  ['WCF Misconfiguration: Anonymous Message Client', 'dotnet', 'wcf_misconfiguration_anonymous_message_client'],
  ['WCF Misconfiguration: Anonymous Transport Client', 'dotnet', 'wcf_misconfiguration_anonymous_transport_client'],
  ['WCF Misconfiguration: Debug Information', 'dotnet', 'wcf_misconfiguration_debug_information'],
  ['WCF Misconfiguration: Insecure Transport', 'dotnet', 'wcf_service_provider_misconfiguration_insecure_transport'],
  ['WCF Misconfiguration: Insufficient Audit Failure Handling', 'dotnet', 'wcf_misconfiguration_insufficient_audit_failure_handling'],
  ['WCF Misconfiguration: Insufficient Logging', 'dotnet', 'wcf_misconfiguration_insufficient_logging'],
  ['WCF Misconfiguration: MSMQ Anonymous Transport Client', 'dotnet', 'wcf_misconfiguration_msmq_anonymous_transport_client'],
  ['WCF Misconfiguration: Metadata', 'dotnet', 'wcf_misconfiguration_metadata'],
  ['WCF Misconfiguration: Security Not Enabled', 'dotnet', 'wcf_misconfiguration_security_not_enabled'],
  ['WCF Misconfiguration: Service Enumeration', 'dotnet', 'wcf_misconfiguration_service_enumeration'],
  ['WCF Misconfiguration: Throttling Not Enabled', 'dotnet', 'wcf_misconfiguration_throttling_not_enabled'],
  ['WCF Misconfiguration: Transport Security Enabled', 'dotnet', 'wcf_misconfiguration_transport_security_enabled'],
  ['WCF Misconfiguration: Unauthorized Access', 'dotnet', 'wcf_misconfiguration_unauthorized_access'],
  ['WCF Misconfiguration: Unsafe Revocation Mode', 'dotnet', 'wcf_misconfiguration_unsafe_revocation_mode'],
  ['WCF Misconfiguration: Weak Token', 'dotnet', 'wcf_misconfiguration_weak_token'],
  ['WSE Misconfiguration: Insufficient Encryption', 'dotnet', 'wse_misconfiguration_insufficient_encryption'],
  ['WSE Misconfiguration: Missing Authorization', 'dotnet', 'wse_misconfiguration_missing_authorization'],
  ['WSE Misconfiguration: Unsigned Fault Timestamp', 'dotnet', 'wse_misconfiguration_unsigned_fault_timestamp'],
  ['WSE Misconfiguration: Unsigned Request Timestamp', 'dotnet', 'wse_misconfiguration_unsigned_request_timestamp'],
  ['WSE Misconfiguration: Unsigned Response Timestamp', 'dotnet', 'wse_misconfiguration_unsigned_response_timestamp'],
  ['Poor Error Handling: Empty Catch Block', 'dotnet', 'poor_error_handling_empty_catch_block'],
  ['Poor Error Handling: Overly Broad Catch', 'dotnet', 'poor_error_handling_overly_broad_catch_block'],
  ['Poor Error Handling: Program Catches NullReferenceException', 'dotnet', 'poor_error_handling_program_catches_nullreferenceexception'],
  ['ASP.NET Bad Practices: Unvalidated Web API Model', 'dotnet', 'asp_dotnet_bad_practices_unvalidated_web_api_model'],
  ['Command Injection', 'dotnet', 'command_injection'],
  ['Cross-Site Scripting: Persistent', 'dotnet', 'cross_site_scripting_persistent'],
  ['Cross-Site Scripting: Poor Validation', 'dotnet', 'cross_site_scripting_poor_validation'],
  ['Cross-Site Scripting: Reflected', 'dotnet', 'cross_site_scripting_reflected'],
  ['Dangerous File Inclusion', 'dotnet', 'dangerous_file_inclusion'],
  ['Denial of Service', 'dotnet', 'denial_of_service'],
  ['Dynamic Code Evaluation: Script Injection', 'dotnet', 'dynamic_code_evaluation_script_injection'],
  ['Header Manipulation', 'dotnet', 'header_manipulation'],
  ['Header Manipulation: Cookies', 'dotnet', 'header_manipulation_cookies'],
  ['LDAP Injection', 'dotnet', 'ldap_injection'],
  ['LDAP Manipulation', 'dotnet', 'ldap_manipulation'],
  ['Log Forging', 'dotnet', 'log_forging'],
  ['Missing XML Validation', 'dotnet', 'missing_xml_validation'],
  ['Missing XML Validation(validating_reader)', 'dotnet', 'missing_xml_validation_validating_reader'],
  ['Often Misused: File Upload', 'dotnet', 'often_misused_file_upload'],
  ['Open Redirect', 'dotnet', 'open_redirect'],
  ['Path Manipulation', 'dotnet', 'path_manipulation'],
  ['Resource Injection', 'dotnet', 'resource_injection'],
  ['SQL Injection', 'dotnet', 'sql_injection'],
  ['SQL Injection: Castle ActiveRecord', 'dotnet', 'sql_injection_castleActiveRecord'],
  ['SQL Injection: LINQ', 'dotnet', 'sql_injection_linq'],
  ['SQL Injection: NHibernate', 'dotnet', 'sql_injection_nhibernate'],
  ['SQL Injection: SubSonic', 'dotnet', 'sql_injection_subsonic'],
  ['Setting Manipulation', 'dotnet', 'setting_manipulation'],
  ['Unsafe Native Invoke', 'dotnet', 'unsafe_native_invoke'],
  ['Unsafe Reflection', 'dotnet', 'unsafe_reflection'],
  ['Value Shadowing', 'dotnet', 'value_shadowing'],
  ['Value Shadowing: Server Variable', 'dotnet', 'value_shadowing_server_variable'],
  ['XML Entity Expansion Injection', 'dotnet', 'xee_injection'],
  ['XML External Entity Injection', 'dotnet', 'xxe_injection'],
  ['XML Injection', 'dotnet', 'xml_injection'],
  ['XPath Injection', 'dotnet', 'xpath_injection'],
  ['ASP.NET Bad Practices: Use of Impersonation Context', 'dotnet', 'asp_dotnet_bad_practices_use_of_impersonation_context'],
  ['ASP.NET Misconfiguration: Header Checking Disabled(header_checking_disabled)', 'dotnet', 'asp_dotnet_misconfiguration_header_checking_disabled'],
  ['ASP.NET Misconfiguration: Missing Error Handling', 'dotnet', 'asp_dotnet_misconfiguration_missing_error_handling'],
  ['ASP.NET Misconfiguration: Persistent Authentication', 'dotnet', 'asp_dotnet_misconfiguration_persistent_authentication'],
  ['ASP.NET Misconfiguration: ViewStateMac Disabled', 'dotnet', 'asp_net_misconfiguration_viewstatemac_disabled'],
  ['ASP.NET Misconfiguration: ViewStateMac Disabled(viewstatemac_disabled)', 'dotnet', 'asp_dotnet_misconfiguration_viewstatemac_disabled'],
  ['Access Control: Anonymous LDAP Bind', 'dotnet', 'access_control_anonymous_ldap_bind'],
  ['Access Control: Database', 'dotnet', 'access_control_database'],
  ['Access Control: LDAP', 'dotnet', 'access_control_ldap'],
  ['Cookie Security: Cookie not Sent Over SSL', 'dotnet', 'cookie_security_cookie_not_sent_over_ssl'],
  ['Cookie Security: HTTPOnly not Set', 'dotnet', 'cookie_security_httponly_not_set'],
  ['Cookie Security: Overly Broad Domain', 'dotnet', 'cookie_security_overly_broad_domain'],
  ['Cookie Security: Overly Broad Path', 'dotnet', 'cookie_security_overly_broad_path'],
  ['Cookie Security: Persistent Cookie', 'dotnet', 'cookie_security_persistent_cookie'],
  ['HTTP Verb Tampering', 'dotnet', 'http_verb_tampering'],
  ['Header Checking Disabled', 'dotnet', 'asp_dotnet_misconfiguration_unsafe_header_parsing'],
  ['Insecure Randomness', 'dotnet', 'insecure_randomness'],
  ['Password Management', 'dotnet', 'password_management'],
  ['Password Management: Empty Password', 'dotnet', 'password_management_empty_password'],
  ['Password Management: Hardcoded Password', 'dotnet', 'password_management_hardcoded_password'],
  ['Password Management: Null Password', 'dotnet', 'password_management_null_password'],
  ['Password Management: Password in Comment', 'dotnet', 'password_management_password_in_comment'],
  ['Password Management: Weak Cryptography', 'dotnet', 'password_management_weak_cryptography'],
  ['Privacy Violation', 'dotnet', 'privacy_violation'],
  ['Privacy Violation: Heap Inspection', 'dotnet', 'privacy_violation_heap_inspection_master'],
  ['Privacy Violation: Image', 'dotnet', 'privacy_violation_image'],
  ['WCF Misconfiguration: Weak Class Reference', 'dotnet', 'wcf_misconfiguration_weak_class_reference'],
  ['Weak Cryptographic Hash', 'dotnet', 'weak_cryptographic_hash'],
  ['Weak Encryption', 'dotnet', 'weak_encryption'],
  ['Weak Encryption: Inadequate RSA Padding', 'dotnet', 'weak_encryption_inadequate_rsa_padding'],
  ['Weak Encryption: Insufficient Key Size', 'dotnet', 'weak_encryption_insufficient_key_size'],
  ['Code Correctness: Negative Content-Length', 'javascript', 'api_abuse_code_correctness_negative_content_length'],
  ['Cross-Session Contamination', 'javascript', 'cross_session_contamination'],
  ['Cross-Site Request Forgery', 'javascript', 'csrf'],
  ['HTML5: Overly Permissive Message Posting Policy', 'javascript', 'html5_overly_permissive_message_posting_policy'],
  ['JavaScript Hijacking: Ad Hoc Ajax', 'javascript', 'javascript_hijacking_ad_hoc_ajax'],
  ['Cross-Site Scripting: DOM', 'javascript', 'cross_site_scripting_dom'],
  ['Cross-Site Scripting: Poor Validation', 'javascript', 'cross_site_scripting_poor_validation'],
  ['Denial of Service', 'javascript', 'denial_of_service'],
  ['Dynamic Code Evaluation: Code Injection', 'javascript', 'dynamic_code_evaluation_code_injection'],
  ['Header Manipulation', 'javascript', 'header_manipulation'],
  ['Header Manipulation: Cookies', 'javascript', 'header_manipulation_cookies'],
  ['Open Redirect', 'javascript', 'open_redirect'],
  ['Path Manipulation', 'javascript', 'path_manipulation'],
  ['Resource Injection', 'javascript', 'resource_injection'],
  ['SQL Injection', 'javascript', 'sql_injection'],
  ['Access Control: Database', 'javascript', 'access_control_database'],
  ['HTML5: Easy-to-Guess Database Name', 'javascript', 'html5_easy_to_guess_database_name'],
  ['Insecure Randomness', 'javascript', 'insecure_randomness'],
  ['Password Management', 'javascript', 'password_management'],
  ['Password Management: Empty Password', 'javascript', 'password_management_empty_password'],
  ['Password Management: Hardcoded Password', 'javascript', 'password_management_hardcoded_password'],
  ['Password Management: Null Password', 'javascript', 'password_management_null_password'],
  ['Password Management: Password in Comment', 'javascript', 'password_management_password_in_comment'],
  ['Password Management: Weak Cryptography', 'javascript', 'password_management_weak_cryptography'],
  ['Privacy Violation', 'javascript', 'privacy_violation'],
  ['Weak Cryptographic Hash', 'javascript', 'weak_cryptographic_hash'],
  ['Weak Encryption', 'javascript', 'weak_encryption'],
  ['Weak Encryption: Insufficient Key Size', 'javascript', 'weak_encryption_insufficient_key_size'],
  ['Portability Flaw: File Separator', 'python', 'portability_flaw_file_separator'],
  ['HTML5: Overly Permissive CORS Policy', 'python', 'html5_overly_permissive_cors_policy'],
  ['System Information Leak', 'python', 'system_information_leak'],
  ['Command Injection', 'python', 'command_injection'],
  ['Cross-Site Scripting: Persistent', 'python', 'cross_site_scripting_persistent'],
  ['Cross-Site Scripting: Poor Validation', 'python', 'cross_site_scripting_poor_validation'],
  ['Cross-Site Scripting: Reflected', 'python', 'cross_site_scripting_reflected'],
  ['Header Manipulation', 'python', 'header_manipulation'],
  ['Log Forging', 'python', 'log_forging'],
  ['Open Redirect', 'python', 'open_redirect'],
  ['Path Manipulation', 'python', 'path_manipulation'],
  ['Resource Injection', 'python', 'resource_injection'],
  ['SQL Injection', 'python', 'sql_injection'],
  ['Insecure Randomness', 'python', 'insecure_randomness'],
  ['Password Management: Hardcoded Password', 'python', 'password_management_hardcoded_password'],
  ['Password Management: Password in Comment', 'python', 'password_management_password_in_comment'],
  ['Weak Cryptographic Hash', 'python', 'weak_cryptographic_hash'],
  ['Dangerous Function', 'sql', 'dangerous_function_exec_ddl'],
  ['Dangerous Function: xp_cmdshell', 'sql', 'dangerous_function_xp_cmdshell'],
  ['SQL Bad Practices: Underspecified Identifier', 'sql', 'sql_bad_practices_underspecified_identifier'],
  ['Code Correctness: Erroneous Null Comparison', 'sql', 'code_correctness_erroneous_null_comparison_tsql'],
  ['Unreleased Resource', 'sql', 'unreleased_resource'],
  ['Unreleased Resource: Cursor Snarfing', 'sql', 'unreleased_resource_cursor_snarfing'],
  ['System Information Leak', 'sql', 'system_information_leak'],
  ['Trust Boundary Violation', 'sql', 'trust_boundary_violation'],
  ['Poor Error Handling: Empty Default Exception Handler', 'sql', 'poor_error_handling_empty_default_exception_handler'],
  ['Cross-Site Scripting: Persistent', 'sql', 'cross_site_scripting_persistent'],
  ['Cross-Site Scripting: Poor Validation', 'sql', 'cross_site_scripting_poor_validation'],
  ['Cross-Site Scripting: Reflected', 'sql', 'cross_site_scripting_reflected'],
  ['Denial of Service', 'sql', 'denial_of_service'],
  ['Header Manipulation', 'sql', 'header_manipulation'],
  ['Resource Injection', 'sql', 'resource_injection'],
  ['SQL Injection', 'sql', 'sql_injection'],
  ['Access Control: Database', 'sql', 'access_control_database'],
  ['Insecure Randomness', 'sql', 'insecure_randomness'],
  ['Password Management', 'sql', 'password_management'],
  ['Password Management: Empty Password', 'sql', 'password_management_empty_password'],
  ['Password Management: Hardcoded Password', 'sql', 'password_management_hardcoded_password'],
  ['Password Management: Null Password', 'sql', 'password_management_null_password'],
  ['Password Management: Password in Comment', 'sql', 'password_management_password_in_comment'],
  ['Privacy Violation', 'sql', 'privacy_violation'],
  ['Privilege Management: Default Function or Procedure Rights', 'sql', 'privilege_management_default_function_or_procedure_rights'],
  ['Privilege Management: Default Package Rights', 'sql', 'privilege_management_default_package_rights'],
  ['Privilege Management: Overly Broad Grant', 'sql', 'privilege_management_overly_broad_grant'],
  ['Weak Cryptographic Hash', 'sql', 'weak_cryptographic_hash'],
  ['HTML5: Overly Permissive CORS Policy', 'vb', 'html5_overly_permissive_cors_policy'],
  ['System Information Leak', 'vb', 'system_information_leak'],
  ['Trust Boundary Violation', 'vb', 'trust_boundary_violation'],
  ['Command Injection', 'vb', 'command_injection'],
  ['Cross-Site Scripting: Persistent', 'vb', 'cross_site_scripting_persistent'],
  ['Cross-Site Scripting: Poor Validation', 'vb', 'cross_site_scripting_poor_validation'],
  ['Cross-Site Scripting: Reflected', 'vb', 'cross_site_scripting_reflected'],
  ['Dynamic Code Evaluation: Script Injection', 'vb', 'dynamic_code_evaluation_code_injection'],
  ['Header Manipulation', 'vb', 'header_manipulation'],
  ['Header Manipulation: Cookies', 'vb', 'header_manipulation_cookies'],
  ['Log Forging', 'vb', 'log_forging'],
  ['Open Redirect', 'vb', 'open_redirect'],
  ['Path Manipulation', 'vb', 'path_manipulation'],
  ['Resource Injection', 'vb', 'resource_injection'],
  ['SQL Injection', 'vb', 'sql_injection'],
  ['Setting Manipulation', 'vb', 'setting_manipulation'],
  ['Unsafe Reflection', 'vb', 'unsafe_reflection'],
  ['Access Control: Database', 'vb', 'access_control_database'],
  ['Insecure Randomness', 'vb', 'insecure_randomness'],
  ['Password Management', 'vb', 'password_management'],
  ['Password Management: Empty Password', 'vb', 'password_management_empty_password'],
  ['Password Management: Hardcoded Password', 'vb', 'password_management_hardcoded_password'],
  ['Password Management: Null Password', 'vb', 'password_management_null_password'],
  ['Password Management: Password in Comment', 'vb', 'password_management_password_in_comment'],
  ['Password Management: Weak Cryptography', 'vb', 'password_management_weak_cryptography'],
  ['Privacy Violation', 'vb', 'privacy_violation'],
  ['Weak Cryptographic Hash', 'vb', 'weak_cryptographic_hash'],
  ['Weak Encryption', 'vb', 'weak_encryption'],
  ['Weak Encryption: Insufficient Key Size', 'vb', 'weak_encryption_insufficient_key_size'],
  ['ASP.NET Bad Practices: Non-Serializable Object Stored in Session', 'dotnet', 'asp_dotnet_bad_practices_non_serializable_object_stored_in_session'],
  ['ADF Faces Bad Practices: unsecure Attribute', 'java', 'adf_faces_bad_practices_unsecure_attribute'],
  ['Castor Bad Practices: Query Mode Not Read-Only', 'java', 'castor_bad_practices_query_mode_not_read_only'],
  ['Castor Bad Practices: Unspecified Query Mode', 'java', 'castor_bad_practices_unspecified_query_mode'],
  ['Code Correctness: Call to System.gc()', 'java', 'code_correctness_call_to_system_gc'],
  ['Code Correctness: Class Does Not Implement equals', 'java', 'code_correctness_class_does_not_implement_equals'],
  ['Code Correctness: Erroneous finalize() Method', 'java', 'code_correctness_erroneous_finalize_method'],
  ['Code Correctness: Multiple Stream Commits', 'java', 'code_correctness_multiple_stream_commits'],
  ['Code Correctness: Negative Content-Length', 'java', 'api_abuse_code_correctness_negative_content_length'],
  ['Code Correctness: toString on Array', 'java', 'code_correctness_tostring_on_array'],
  ['Dangerous Field', 'java', 'dangerous_field'],
  ['Dangerous Method', 'java', 'dangerous_method'],
  ['Dangerous Type', 'java', 'dangerous_class_function'],
  ['EJB Bad Practices: Use of Class Loader', 'java', 'ejb_bad_practices_use_of_classloader'],
  ['EJB Bad Practices: Use of Sockets', 'java', 'ejb_bad_practices_use_of_sockets'],
  ['EJB Bad Practices: Use of Synchronization Primitives', 'java', 'ejb_bad_practices_use_of_synchronization_primitives'],
  ['EJB Bad Practices: Use of java.io', 'java', 'ejb_bad_practices_use_of_java_io'],
  ['File Disclosure: J2EE', 'java', 'file_disclosure_j2ee'],
  ['File Disclosure: Spring', 'java', 'file_disclosure_spring'],
  ['File Disclosure: Spring Webflow', 'java', 'file_disclosure_spring_webflow'],
  ['File Disclosure: Struts', 'java', 'file_disclosure_struts'],
  ['Immutable Classes: Field Mutation', 'java', 'immutable_field_mutation'],
  ['Immutable Classes: Non-final Fields', 'java', 'immutable_non_final_fields'],
  ['Immutable Classes: Public Mutable Fields', 'java', 'immutable_public_mutable_fields'],
  ['J2EE Bad Practices: Sockets', 'java', 'j2ee_badpractices_sockets'],
  ['J2EE Bad Practices: getConnection()', 'java', 'j2ee_badpractices_getconnection'],
  ['Missing Check against Null', 'java', 'missing_check_against_null'],
  ['Missing Check for Null Parameter', 'java', 'missing_check_for_null_parameter'],
  ['Object Model Violation: Erroneous clone() Method', 'java', 'object_model_violation_erroneous_clone_method'],
  ['Object Model Violation: Just one of equals() and hashCode() Defined', 'java', 'object_model_violation_just_one_of_equals_hashcode_defined'],
  ['Object Model Violation: Just one of restoreState() and saveState() Defined', 'java', 'object_model_violation_just_one_of_restoreState_saveState_defined'],
  ['Obsolete: Deprecated by ESAPI', 'java', 'obsolete_deprecated_by_esapi'],
  ['Often Misused: Authentication', 'java', 'often_misused_authentication'],
  ['Often Misused: Boolean.getBoolean()', 'java', 'often_misused_boolean_getboolean'],
  ['Often Misused: Encoding', 'java', 'often_misued_encoding'],
  ['Often Misused: Spring Remote Service', 'java', 'often_misused_spring_remote_service'],
  ['Often Misused: Spring Web Service', 'java', 'often_misused_spring_web_service'],
  ['Password Management: Weak Redundancy', 'java', 'password_management_weak_redundancy'],
  ['Poor Style: Explicit Call to finalize()', 'java', 'poor_style_explicit_call_to_finalize'],
  ['Spring MVC Bad Practices: Request Parameters Bound into Persisted Objects', 'java', 'spring_mvc_bad_practices_request_parameters_bound_into_persisted_objects'],
  ['Struts 2 Bad Practices: Request Map Tampering', 'java', 'struts2_bad_practice_runtime_data_tampering'],
  ['Unchecked Return Value', 'java', 'unchecked_return_value'],
  ['Android Bad Practices: Use of Released Camera Resource', 'java', 'android_bad_practices_use_of_released_camera_resource'],
  ['Android Bad Practices: Use of Released Media Resource', 'java', 'android_bad_practices_use_of_released_media_resource'],
  ['Android Bad Practices: Use of Released SQLite Resource', 'java', 'android_bad_practices_use_of_released_sqlite_resource'],
  ['Code Correctness: Call to Thread.run()', 'java', 'code_correctness_call_to_thread_run'],
  ['Code Correctness: Call to notify()', 'java', 'code_correctness_call_to_notify'],
  ['Code Correctness: Class Does Not Implement Cloneable', 'java', 'code_correctness_class_does_not_implement_cloneable'],
  ['Code Correctness: Erroneous Class Compare', 'java', 'code_correctness_erroneous_class_compare'],
  ['Code Correctness: Erroneous Negative Value', 'java', 'erroneous_negative_value_variable'],
  ['Code Correctness: Erroneous String Compare', 'java', 'code_correctness_erroneous_string_compare'],
  ['Code Correctness: Erroneous Zero Value', 'java', 'erroneous_zero_value_variable'],
  ['Code Correctness: Incorrect serialPersistentFields Modifier', 'java', 'code_correctness_incorrect_serialpersistentfields_modifier'],
  ['Code Correctness: Misspelled Method Name', 'java', 'code_correctness_misspelled_method_name'],
  ['Code Correctness: Non-Synchronized Method Overrides Synchronized Method', 'java', 'code_correctness_non_synchronized_method_overrides'],
  ['Code Correctness: Regular Expressions Denial of Service', 'java', 'denial_of_service_regex_evaluation'],
  ['Code Correctness: null Argument to equals()', 'java', 'code_correctness_null_argument_to_equals'],
  ['Dead Code: Empty Try Block', 'java', 'dead_code_empty_try_block'],
  ['Dead Code: Expression is Always false', 'java', 'dead_code_expression_is_always_false'],
  ['Dead Code: Expression is Always true', 'java', 'dead_code_expression_is_always_true'],
  ['Dead Code: Unused Field', 'java', 'dead_code_unused_field'],
  ['Dead Code: Unused Method', 'java', 'dead_code_unused_method'],
  ['Null Dereference', 'java', 'null_dereference_dereference_after_store'],
  ['Obsolete', 'java', 'obsolete'],
  ['Poor Style: Confusing Naming(class_and_member)', 'java', 'poor_style_confusing_naming_class_and_member'],
  ['Poor Style: Confusing Naming(member_and_method)', 'java', 'poor_style_confusing_naming_member_and_method'],
  ['Poor Style: Empty Synchronized Block', 'java', 'poor_style_empty_synchronized_block'],
  ['Poor Style: Identifier Contains Dollar Symbol ($)', 'java', 'poor_style_identifier_contains_dollar_symbol'],
  ['Poor Style: Redundant Initialization', 'java', 'poor_style_redundant_initialization'],
  ['Poor Style: Value Never Read', 'java', 'poor_style_value_never_read'],
  ['Portability Flaw: File Separator', 'java', 'portability_flaw_file_separator'],
  ['Redundant Null Check', 'java', 'null_dereference_check_after_dereference'],
  ['Unreleased Resource: Android Camera', 'java', 'unreleased_resource_android_camera'],
  ['Unreleased Resource: Android Media', 'java', 'unreleased_resource_android_media'],
  ['Unreleased Resource: Android SQLite Database', 'java', 'unreleased_resource_android_sqlite_database'],
  ['Unreleased Resource: Files', 'java', 'unreleased_resource_files'],
  ['Unreleased Resource: Sockets', 'java', 'unreleased_resource_sockets'],
  ['Unreleased Resource: Streams', 'java', 'unreleased_resource'],
  ['Unreleased Resource: Synchronization', 'java', 'unreleased_resource_synchronization'],
  ['ADF Bad Practices: Default url-invoke-disallowed Setting', 'java', 'adf_bad_practices_default_url_invoke_disallowed_setting'],
  ['Cross-Site Request Forgery', 'java', 'csrf'],
  ['HTML5: Overly Permissive CORS Policy', 'java', 'html5_overly_permissive_cors_policy'],
  ['Hidden Field', 'java', 'hidden_field'],
  ['Insecure Storage: Android Backup Storage', 'java', 'insecure_storage_android_backup_storage'],
  ['Insecure Storage: Android External Storage', 'java', 'insecure_storage_android_external_storage'],
  ['Insecure Storage: Android World Readable or Writeable', 'java', 'insecure_storage_android_world_readable_or_writeable'],
  ['Insecure Transport', 'java', 'insecure_transport'],
  ['J2EE Bad Practices: Leftover Debug Code', 'java', 'j2ee_badpractices_leftover_debug_code'],
  ['JavaScript Hijacking: Ad Hoc Ajax', 'java', 'javascript_hijacking_ad_hoc_ajax'],
  ['JavaScript Hijacking: Vulnerable Framework', 'java', 'javascript_hijacking_vulnerable_framework'],
  ['Poor Logging Practice: Logger Not Declared Static Final', 'java', 'poor_logging_practice_logger_is_not_declared_static_final'],
  ['Poor Logging Practice: Multiple Loggers', 'java', 'poor_logging_practice_multiple_loggers'],
  ['Poor Logging Practice: Use of a System Output Stream', 'java', 'poor_logging_practice_use_of_a_system_output_stream'],
  ['Poor Style: Non-final Public Static Field', 'java', 'poor_style_non-final_public_static_field'],
  ['System Information Leak', 'java', 'system_information_leak'],
  ['System Information Leak: Apache Axis', 'java', 'system_information_leak_apache_axis'],
  ['System Information Leak: Apache Axis 2', 'java', 'system_information_leak_apache_axis2'],
  ['System Information Leak: HTML Comment in JSP', 'java', 'system_information_leak_html_comment_in_jsp'],
  ['System Information Leak: Incomplete Servlet Error Handling', 'java', 'system_information_leak_incomplete_servlet_error_handling'],
  ['System Information Leak: Overly Broad SQL Logging', 'java', 'system_information_leak_overly_broad_sql_logging'],
  ['Trust Boundary Violation', 'java', 'trust_boundary_violation'],
  ['Unsafe Mobile Code: Access Violation', 'java', 'unsafe_mobile_code_access_violation'],
  ['Unsafe Mobile Code: Database Access', 'java', 'unsafe_mobile_code_database_access'],
  ['Unsafe Mobile Code: Inner Class', 'java', 'unsafe_mobile_code_inner_class'],
  ['Unsafe Mobile Code: Public finalize() Method', 'java', 'unsafe_mobile_code_public_finalize_method'],
  ['Unsafe Mobile Code: Unsafe Array Declaration', 'java', 'unsafe_mobile_code_unsafe_array_declaration'],
  ['Unsafe Mobile Code: Unsafe Public Field', 'java', 'unsafe_mobile_code_unsafe_public_field'],
  ['Android Misconfiguration: Debug Information', 'java', 'android_misconfiguration_debug_information'],
  ['Axis 2 Misconfiguration: Debug Information', 'java', 'axis2_misconfiguration_debug_information'],
  ['Axis 2 Misconfiguration: Insecure Message Security', 'java', 'axis2_misconfiguration_insecure_message_security'],
  ['Axis 2 Misconfiguration: Insecure Transport Receiver', 'java', 'axis2_misconfiguration_insecure_transport_receiver'],
  ['Axis 2 Misconfiguration: Insecure Transport Sender', 'java', 'axis2_misconfiguration_insecure_transport_sender'],
  ['Axis 2 Service Provider Misconfiguration: Inbound WS-Security Not Enabled', 'java', 'axis2_service_provider_misconfiguration_inbound_ws-security_not_enabled'],
  ['Axis 2 Service Provider Misconfiguration: Missing Inbound Encryption', 'java', 'axis2_service_provider_misconfiguration_missing_inbound_encryption'],
  ['Axis 2 Service Provider Misconfiguration: Missing Inbound Signature', 'java', 'axis2_service_provider_misconfiguration_missing_inbound_signature'],
  ['Axis 2 Service Provider Misconfiguration: Missing Inbound Timestamp', 'java', 'axis2_service_provider_misconfiguration_missing_inbound_timestamp'],
  ['Axis 2 Service Provider Misconfiguration: Missing Outbound Encryption', 'java', 'axis2_service_provider_misconfiguration_missing_outbound_encryption'],
  ['Axis 2 Service Provider Misconfiguration: Missing Outbound Signature', 'java', 'axis2_service_provider_misconfiguration_missing_outbound_signature'],
  ['Axis 2 Service Provider Misconfiguration: Missing Outbound Timestamp', 'java', 'axis2_service_provider_misconfiguration_missing_outbound_timestamp'],
  ['Axis 2 Service Provider Misconfiguration: Outbound WS-Security Not Enabled', 'java', 'axis2_service_provider_misconfiguration_outbound_ws-security_not_enabled'],
  ['Axis 2 Service Provider Misconfiguration: Unsigned Inbound Timestamp', 'java', 'axis2_service_provider_misconfiguration_unsigned_inbound_timestamp'],
  ['Axis 2 Service Provider Misconfiguration: Unsigned Outbound Timestamp', 'java', 'axis2_service_provider_misconfiguration_unsigned_outbound_timestamp'],
  ['Axis 2 Service Provider Misconfiguration: WS-Security Not Enabled', 'java', 'axis2_service_provider_misconfiguration_ws-security_not_enabled'],
  ['Axis 2 Service Provider Misconfiguration: Weak Token', 'java', 'axis2_service_provider_misconfiguration_weak_token'],
  ['Axis 2 Service Requester Misconfiguration: Inbound WS-Security Not Enabled', 'java', 'axis2_service_requester_misconfiguration_inbound_ws-security_not_enabled'],
  ['Axis 2 Service Requester Misconfiguration: Missing Inbound Encryption', 'java', 'axis2_service_requester_misconfiguration_missing_inbound_encryption'],
  ['Axis 2 Service Requester Misconfiguration: Missing Inbound Signature', 'java', 'axis2_service_requester_misconfiguration_missing_inbound_signature'],
  ['Axis 2 Service Requester Misconfiguration: Missing Inbound Timestamp', 'java', 'axis2_service_requester_misconfiguration_missing_inbound_timestamp'],
  ['Axis 2 Service Requester Misconfiguration: Missing Outbound Encryption', 'java', 'axis2_service_requester_misconfiguration_missing_outbound_encryption'],
  ['Axis 2 Service Requester Misconfiguration: Missing Outbound Signature', 'java', 'axis2_service_requester_misconfiguration_missing_outbound_signature'],
  ['Axis 2 Service Requester Misconfiguration: Missing Outbound Timestamp', 'java', 'axis2_service_requester_misconfiguration_missing_outbound_timestamp'],
  ['Axis 2 Service Requester Misconfiguration: Outbound WS-Security Not Enabled', 'java', 'axis2_service_requester_misconfiguration_outbound_ws-security_not_enabled'],
  ['Axis 2 Service Requester Misconfiguration: Plain Text Password', 'java', 'axis2_service_requester_misconfiguration_plain_text_password'],
  ['Axis 2 Service Requester Misconfiguration: Unsigned Inbound Timestamp', 'java', 'axis2_service_requester_misconfiguration_unsigned_inbound_timestamp'],
  ['Axis 2 Service Requester Misconfiguration: Unsigned Outbound Timestamp', 'java', 'axis2_service_requester_misconfiguration_unsigned_outbound_timestamp'],
  ['Axis 2 Service Requester Misconfiguration: WS-Security Not Enabled', 'java', 'axis2_service_requester_misconfiguration_ws-security_not_enabled'],
  ['Axis 2 Service Requester Misconfiguration: Weak Token', 'java', 'axis2_service_requester_misconfiguration_weak_token'],
  ['Axis Misconfiguration: Debug Information', 'java', 'axis_misconfiguration_debug_information'],
  ['Axis Misconfiguration: Service Enumeration', 'java', 'axis_misconfiguration_service_enumeration'],
  ['Axis Service Provider Misconfiguration: Plain Text Password', 'java', 'axis_service_provider_misconfiguration_plain_text_password'],
  ['Axis Service Provider Misconfiguration: Weak Token', 'java', 'axis_service_provider_misconfiguration_weak_token'],
  ['Axis Service Requester Misconfiguration: Plain Text Password', 'java', 'axis_service_requester_misconfiguration_plain_text_password'],
  ['Axis Service Requester Misconfiguration: Weak Token', 'java', 'axis_service_requester_misconfiguration_weak_token'],
  ['Build Misconfiguration: Dynamic Dependency Version Usage', 'java', 'build_misconfiguration_dynamic_dependency_version'],
  ['Build Misconfiguration: External Ant Dependency Repository', 'java', 'build_misconfiguration_external_ant_dependency_repository'],
  ['Build Misconfiguration: External Ivy Dependency Repository', 'java', 'build_misconfiguration_external_ivy_dependency_repository'],
  ['Build Misconfiguration: External Maven Dependency Repository', 'java', 'build_misconfiguration_external_maven_dependency_repository'],
  ['Flex Misconfiguration: Debug Information', 'java', 'flex_misconfiguration_debug_information'],
  ['J2EE Misconfiguration: Cookies Disabled', 'java', 'j2ee_misconfiguration_cookies_disabled'],
  ['J2EE Misconfiguration: Debug Information', 'java', 'j2ee_misconfiguration_debug_information'],
  ['J2EE Misconfiguration: Direct JSP Access', 'java', 'j2ee_misconfiguration_direct_jsp_access'],
  ['J2EE Misconfiguration: Duplicate Security Role', 'java', 'j2ee_misconfiguration_duplicate_security_role'],
  ['J2EE Misconfiguration: Duplicate Servlet Mapping', 'java', 'j2ee_misconfiguration_duplicate_servlet_mapping'],
  ['J2EE Misconfiguration: Excessive Servlet Mappings', 'java', 'j2ee_misconfiguration_excessive_servlet_mappings'],
  ['J2EE Misconfiguration: Excessive Session Timeout', 'java', 'j2ee_misconfiguration_excessive_session_timeout'],
  ['J2EE Misconfiguration: Incomplete Error Handling - (404)', 'java', 'j2ee_misconfiguration_missing_error_handling_abs_404'],
  ['J2EE Misconfiguration: Incomplete Error Handling - (500)', 'java', 'j2ee_misconfiguration_missing_error_handling_abs_500'],
  ['J2EE Misconfiguration: Incomplete Error Handling - (throwable)', 'java', 'j2ee_misconfiguration_missing_error_handling_abs_throwable'],
  ['J2EE Misconfiguration: Insecure Transport', 'java', 'j2ee_misconfiguration_insecure_transport'],
  ['J2EE Misconfiguration: Insufficient Session-ID Length', 'java', 'j2ee_misconfiguration_insufficient_session_id_length'],
  ['J2EE Misconfiguration: Invalid Servlet Name', 'java', 'j2ee_misconfiguration_invalid_servlet_name'],
  ['J2EE Misconfiguration: Missing Authentication Method', 'java', 'j2ee_misconfiguration_missing_authentication_method'],
  ['J2EE Misconfiguration: Missing Data Transport Constraint', 'java', 'j2ee_misconfiguration_missing_data_transport_constraint'],
  ['J2EE Misconfiguration: Missing Error Handling', 'java', 'j2ee_misconfiguration_missing_error_handling'],
  ['J2EE Misconfiguration: Missing Filter Definition', 'java', 'j2ee_misconfiguration_missing_filter_definition'],
  ['J2EE Misconfiguration: Missing Security Role', 'java', 'j2ee_misconfiguration_missing_security_role'],
  ['J2EE Misconfiguration: Missing Servlet Mapping', 'java', 'j2ee_misconfiguration_missing_servlet_mapping'],
  ['J2EE Misconfiguration: Unsafe Bean Declaration', 'java', 'j2ee_misconfiguration_unsafe_bean_declaration'],
  ['J2EE Misconfiguration: Weak Access Permissions', 'java', 'j2ee_misconfiguration_weak_access_permissions'],
  ['Password Management: Empty Password in Configuration File', 'java', 'password_management_empty_password_in_configuration_file'],
  ['Password Management: Password in Configuration File', 'java', 'password_management_password_in_configuration_file'],
  ['Struts Misconfiguration: Duplicate Form Bean', 'java', 'struts_misconfiguration_duplicate_form_bean'],
  ['Struts Misconfiguration: Invalid Path', 'java', 'struts_misconfiguration_invalid_path'],
  ['Struts Misconfiguration: Missing Action Input', 'java', 'struts_misconfiguration_missing_action_input'],
  ['Struts Misconfiguration: Missing Exception Type', 'java', 'struts_misconfiguration_missing_exception_type'],
  ['Struts Misconfiguration: Missing Form Bean', 'java', 'struts_misconfiguration_missing_form_bean'],
  ['Struts Misconfiguration: Missing Form Bean Name', 'java', 'struts_misconfiguration_missing_form_bean_name'],
  ['Struts Misconfiguration: Missing Form Bean Type', 'java', 'struts_misconfiguration_missing_form_bean_type'],
  ['Struts Misconfiguration: Missing Form Property Type', 'java', 'struts_misconfiguration_missing_form_property_type'],
  ['Struts Misconfiguration: Missing Forward Name', 'java', 'struts_misconfiguration_missing_forward_name'],
  ['Struts Misconfiguration: Missing Forward Path', 'java', 'struts_misconfiguration_missing_forward_path'],
  ['Tomcat Configuration: Insecure Transport', 'java', 'tomcat_configuration_insecure_transport'],
  ['WebSphere Misconfiguration: Missing Nonce', 'java', 'websphere_misconfiguration_missing_nonce'],
  ['WebSphere Misconfiguration: Servlets Served By Class Name', 'java', 'websphere_misconfiguration_servlets_served_by_class_name'],
  ['WebSphere Service Provider Misconfiguration: Inbound WS-Security Not Enabled', 'java', 'websphere_service_provider_misconfiguration_inbound_ws-security_not_enabled'],
  ['WebSphere Service Provider Misconfiguration: Missing Inbound Encryption', 'java', 'websphere_service_provider_misconfiguration_missing_inbound_encryption'],
  ['WebSphere Service Provider Misconfiguration: Missing Inbound Signature', 'java', 'websphere_service_provider_misconfiguration_missing_inbound_signature'],
  ['WebSphere Service Provider Misconfiguration: Missing Inbound Timestamp', 'java', 'websphere_service_provider_misconfiguration_missing_inbound_timestamp'],
  ['WebSphere Service Provider Misconfiguration: Missing Outbound Encryption', 'java', 'websphere_service_provider_misconfiguration_missing_outbound_encryption'],
  ['WebSphere Service Provider Misconfiguration: Missing Outbound Signature', 'java', 'websphere_service_provider_misconfiguration_missing_outbound_signature'],
  ['WebSphere Service Provider Misconfiguration: Missing Outbound Timestamp', 'java', 'websphere_service_provider_misconfiguration_missing_outbound_timestamp'],
  ['WebSphere Service Provider Misconfiguration: Missing Timestamp Expiration', 'java', 'websphere_service_provider_misconfiguration_missing_timestamp_expiration'],
  ['WebSphere Service Provider Misconfiguration: Outbound WS-Security Not Enabled', 'java', 'websphere_service_provider_misconfiguration_outbound_ws-security_not_enabled'],
  ['WebSphere Service Provider Misconfiguration: Unsigned Inbound Timestamp', 'java', 'websphere_service_provider_misconfiguration_unsigned_inbound_timestamp'],
  ['WebSphere Service Provider Misconfiguration: Unsigned Outbound Timestamp', 'java', 'websphere_service_provider_misconfiguration_unsigned_outbound_timestamp'],
  ['WebSphere Service Provider Misconfiguration: Weak Token', 'java', 'websphere_service_provider_misconfiguration_weak_token'],
  ['WebSphere Service Requester Misconfiguration: Inbound WS-Security Not Enabled', 'java', 'websphere_service_requester_misconfiguration_inbound_ws-security_not_enabled'],
  ['WebSphere Service Requester Misconfiguration: Missing Inbound Encryption', 'java', 'websphere_service_requester_misconfiguration_missing_inbound_encryption'],
  ['WebSphere Service Requester Misconfiguration: Missing Inbound Signature', 'java', 'websphere_service_requester_misconfiguration_missing_inbound_signature'],
  ['WebSphere Service Requester Misconfiguration: Missing Inbound Timestamp', 'java', 'websphere_service_requester_misconfiguration_missing_inbound_timestamp'],
  ['WebSphere Service Requester Misconfiguration: Missing Outbound Encryption', 'java', 'websphere_service_requester_misconfiguration_missing_outbound_encryption'],
  ['WebSphere Service Requester Misconfiguration: Missing Outbound Signature', 'java', 'websphere_service_requester_misconfiguration_missing_outbound_signature'],
  ['WebSphere Service Requester Misconfiguration: Missing Outbound Timestamp', 'java', 'websphere_service_requester_misconfiguration_missing_outbound_timestamp'],
  ['WebSphere Service Requester Misconfiguration: Missing Timestamp Expiration', 'java', 'websphere_service_requester_misconfiguration_missing_timestamp_expiration'],
  ['WebSphere Service Requester Misconfiguration: Outbound WS-Security Not Enabled', 'java', 'websphere_service_requester_misconfiguration_outbound_ws-security_not_enabled'],
  ['WebSphere Service Requester Misconfiguration: Unsigned Inbound Timestamp', 'java', 'websphere_service_requester_misconfiguration_unsigned_inbound_timestamp'],
  ['WebSphere Service Requester Misconfiguration: Unsigned Outbound Timestamp', 'java', 'websphere_service_requester_misconfiguration_unsigned_outbound_timestamp'],
  ['WebSphere Service Requester Misconfiguration: Weak Token', 'java', 'websphere_service_requester_misconfiguration_weak_token'],
  ['Weblogic Misconfiguration: Missing Timestamp', 'java', 'weblogic_misconfiguration_missing_timestamp'],
  ['Weblogic Misconfiguration: Weak Token', 'java', 'weblogic_misconfiguration_weak_token'],
  ['Poor Error Handling: Empty Catch Block', 'java', 'poor_error_handling_empty_catch_block'],
  ['Poor Error Handling: Overly Broad Catch', 'java', 'poor_error_handling_overly_broad_catch'],
  ['Poor Error Handling: Overly Broad Throws', 'java', 'poor_error_handling_overly_broad_throws'],
  ['Poor Error Handling: Program Catches NullPointerException', 'java', 'poor_error_handling_program_catches_nullpointerexception'],
  ['Poor Error Handling: Return Inside Finally', 'java', 'poor_error_handling_return_inside_finally'],
  ['Poor Error Handling: Swallowed ThreadDeath', 'java', 'poor_error_handling_swallowed_threaddeath'],
  ['Poor Error Handling: Throw Inside Finally', 'java', 'poor_error_handling_throw_inside_finally'],
  ['Poor Error Handling: Unhandled SSL Exception', 'java', 'poor_error_handling_unhandled_ssl_exception'],
  ['ADF Bad Practices: Missing URL Parameter Converter', 'java', 'adf_bad_practices_missing_url_parameter_converter'],
  ['Command Injection', 'java', 'command_injection'],
  ['Cross-Site Scripting: DOM', 'java', 'cross_site_scripting_dom'],
  ['Cross-Site Scripting: External Links', 'java', 'xss_external_links'],
  ['Cross-Site Scripting: Persistent', 'java', 'cross_site_scripting_persistent'],
  ['Cross-Site Scripting: Poor Validation', 'java', 'cross_site_scripting_poor_validation'],
  ['Cross-Site Scripting: Reflected', 'java', 'cross_site_scripting_reflected'],
  ['Dangerous File Inclusion', 'java', 'dangerous_file_inclusion'],
  ['Denial of Service', 'java', 'denial_of_service'],
  ['Denial of Service: Parse Double', 'java', 'denial_of_service_parse_double'],
  ['Dynamic Code Evaluation: Code Injection', 'java', 'dynamic_code_evaluation_code_injection'],
  ['Hadoop Cluster Manipulation', 'java', 'hadoop_cluster_manipulation'],
  ['Hadoop Job Manipulation', 'java', 'hadoop_job_manipulation'],
  ['Header Manipulation', 'java', 'header_manipulation'],
  ['Header Manipulation: Cookies', 'java', 'header_manipulation_cookies'],
  ['LDAP Injection', 'java', 'ldap_injection'],
  ['LDAP Manipulation', 'java', 'ldap_manipulation'],
  ['Log Forging', 'java', 'log_forging'],
  ['Missing XML Validation', 'java', 'missing_xml_validation'],
  ['Often Misused: File Upload', 'java', 'often_misused_file_upload'],
  ['Open Redirect', 'java', 'open_redirect'],
  ['Path Manipulation', 'java', 'path_manipulation'],
  ['Process Control', 'java', 'process_control'],
  ['Process Control: Invoker Servlet', 'java', 'process_control_invoker_servlet'],
  ['Query String Injection: Amazon Web Services', 'java', 'query_string_injection_amazon_web_services'],
  ['Query String Injection: Android Provider', 'java', 'query_string_injection_android_provider'],
  ['Resource Injection', 'java', 'resource_injection'],
  ['SQL Injection', 'java', 'sql_injection'],
  ['SQL Injection: Hibernate', 'java', 'sql_injection_hibernate'],
  ['SQL Injection: JDO', 'java', 'sql_injection_jdo'],
  ['SQL Injection: Persistence', 'java', 'sql_injection_persistence'],
  ['SQL Injection: iBatis Data Map', 'java', 'sql_injection_ibatis_data_map'],
  ['Setting Manipulation', 'java', 'setting_manipulation'],
  ['Struts 2: Action Field Without Validator', 'java', 'struts2_action_field_without_validator'],
  ['Struts 2: Duplicate Action Field Validators', 'java', 'struts2_duplicate_action_field_validators'],
  ['Struts 2: Duplicate Validation Files', 'java', 'struts2_duplicate_validation_files'],
  ['Struts 2: Duplicate Validators', 'java', 'struts2_duplicate_validators'],
  ['Struts 2: Undeclared Validator', 'java', 'struts2_undeclared_validator'],
  ['Struts 2: Unvalidated Action', 'java', 'struts2_unvalidated_action'],
  ['Struts 2: Validation File Without Action', 'java', 'struts2_validation_file_without_action'],
  ['Struts 2: Validator Without Action Field', 'java', 'struts2_validator_without_action_field'],
  ['Struts: Duplicate Validation Forms', 'java', 'struts_duplicate_validate_forms'],
  ['Struts: Erroneous validate() Method', 'java', 'struts_erroneous_validate_method'],
  ['Struts: Form Does Not Extend Validation Class', 'java', 'struts_form_does_not_extend_validation_class'],
  ['Struts: Form Field Without Validator', 'java', 'struts_form_field_without_validator'],
  ['Struts: Plugin Framework Not In Use', 'java', 'struts_plugin_framework_not_in_use'],
  ['Struts: Unused Action Form', 'java', 'struts_unused_action_form'],
  ['Struts: Unused Validation Form', 'java', 'struts_unused_validation_form'],
  ['Struts: Unvalidated Action Form', 'java', 'struts_unvalidated_action_form'],
  ['Struts: Validator Turned Off', 'java', 'struts_validator_turned_off'],
  ['Struts: Validator Without Form Field', 'java', 'struts_validator_without_form_field'],
  ['Unsafe JNI', 'java', 'unsafe_jni'],
  ['Unsafe Reflection', 'java', 'unsafe_reflection'],
  ['XML Entity Expansion Injection', 'java', 'xee_injection'],
  ['XML External Entity Injection', 'java', 'xxe_injection'],
  ['XML Injection', 'java', 'xml_injection'],
  ['XPath Injection', 'java', 'xpath_injection'],
  ['Access Control: Amazon Web Services', 'java', 'access_control_amazon_web_services'],
  ['Access Control: Android Provider', 'java', 'access_control_android_provider'],
  ['Access Control: Anonymous LDAP Bind', 'java', 'access_control_anonymous_ldap_bind'],
  ['Access Control: Database', 'java', 'access_control_database'],
  ['Access Control: LDAP', 'java', 'access_control_ldap'],
  ['Access Control: SecurityManager Bypass', 'java', 'access_control_securitymanager_bypass'],
  ['Access Control: Weak Security Constraint', 'java', 'access_control_weak_security_constraint'],
  ['Acegi Misconfiguration: Insecure Channel Mixing', 'java', 'acegi_misconfiguration_insecure_channel_mixing'],
  ['Acegi Misconfiguration: Run-As Authentication Replacement', 'java', 'acegi_misconfiguration_run_as_authentication_replacement'],
  ['Android Bad Practices: Application Permission Defined', 'java', 'android_bad_practices_application_permission_defined'],
  ['Android Bad Practices: Just Provider writePermission Defined', 'java', 'android_bad_practices_just_provider_writepermission_defined'],
  ['Android Bad Practices: Missing Broadcaster Permission', 'java', 'android_bad_practices_missing_broadcaster_permission'],
  ['Android Bad Practices: Missing Component Permission', 'java', 'android_bad_practices_missing_component_permission'],
  ['Android Bad Practices: Missing Exported Flag or Component Permission', 'java', 'android_bad_practices_missing_exported_flag_or_component_permission'],
  ['Android Bad Practices: Missing Receiver Permission', 'java', 'android_bad_practices_missing_receiver_permission'],
  ['Android Bad Practices: Provider permission Defined', 'java', 'android_bad_practices_provider_permission_defined'],
  ['Android Bad Practices: Sticky Broadcast', 'java', 'android_bad_practices_sticky_broadcast'],
  ['Android Bad Practices: Weak Authentication', 'java', 'android_bad_practices_weak_authentication'],
  ['Android Bad Practices: normal Permission', 'java', 'android_bad_practices_normal_permission'],
  ['Cookie Security: Cookie not Sent Over SSL', 'java', 'cookie_security_cookie_not_sent_over_ssl'],
  ['Cookie Security: Overly Broad Domain', 'java', 'cookie_security_overly_broad_domain'],
  ['Cookie Security: Overly Broad Path', 'java', 'cookie_security_overly_broad_path'],
  ['Cookie Security: Persistent Cookie', 'java', 'cookie_security_persistent_cookie'],
  ['HTTP Verb Tampering', 'java', 'http_verb_tampering'],
  ['Insecure Randomness', 'java', 'insecure_randomness'],
  ['Insecure Randomness: Poor Seeding', 'java', 'insecure_randomness_poor_seed'],
  ['Insecure SSL: Android Customized Implementation', 'java', 'insecure_ssl_android_customized_implementation'],
  ['Insecure SSL: Android Hostname Verification Disabled', 'java', 'insecure_ssl_android_hostname_verification_disabled'],
  ['Insecure SSL: Android Socket', 'java', 'insecure_ssl_android_socket'],
  ['Missing SecurityManager Check: Cloneable', 'java', 'missing_securitymanager_check_cloneable'],
  ['Missing SecurityManager Check: Serializable', 'java', 'missing_securitymanager_check_serializable'],
  ['Often Misused: Android Permission Check', 'java', 'often_misused_android_permission_check'],
  ['Password Management', 'java', 'password_management'],
  ['Password Management: Empty Password', 'java', 'password_management_empty_password'],
  ['Password Management: Hardcoded Password', 'java', 'password_management_hardcoded_password'],
  ['Password Management: Null Password', 'java', 'password_management_null_password'],
  ['Password Management: Password in Comment', 'java', 'password_management_password_in_comment'],
  ['Password Management: Password in Redirect', 'java', 'password_management_redirect'],
  ['Password Management: Weak Cryptography', 'java', 'password_management_weak_cryptography'],
  ['Privacy Violation', 'java', 'privacy_violation'],
  ['Privacy Violation: Android Internal Storage', 'java', 'privacy_violation_android_internal_storage'],
  ['Privacy Violation: Heap Inspection', 'java', 'privacy_violation_heap_inspection'],
  ['Privacy Violation: Password', 'java', 'privacy_violation_password'],
  ['Privilege Management: Amazon Web Services Unchecked Permissions', 'java', 'privilege_management_amazon_web_services_unchecked_permissions'],
  ['Privilege Management: Android Data Storage', 'java', 'privilege_management_android_data_storage'],
  ['Privilege Management: Android Disable', 'java', 'privilege_management_android_disable'],
  ['Privilege Management: Android Location', 'java', 'privilege_management_android_location'],
  ['Privilege Management: Android Messaging', 'java', 'privilege_management_android_messaging'],
  ['Privilege Management: Android Network', 'java', 'privilege_management_android_network'],
  ['Privilege Management: Android Telephony', 'java', 'privilege_management_android_telephony'],
  ['Privilege Management: Missing API Permission', 'java', 'privilege_management_missing_api_permission'],
  ['Privilege Management: Missing Content Provider Permission', 'java', 'privilege_management_missing_content_provider_permission'],
  ['Privilege Management: Missing Intent Permission', 'java', 'privilege_management_missing_intent_permission'],
  ['Privilege Management: Overly Broad Access Specifier', 'java', 'privilege_management_overly_broad_access_specifier'],
  ['Privilege Management: Unnecessary Permission', 'java', 'privilege_management_unnecessary_permission'],
  ['Weak Cryptographic Hash', 'java', 'weak_cryptographic_hash'],
  ['Weak Cryptographic Hash: Hardcoded Salt', 'java', 'weak_cryptographic_hash_hardcoded_salt'],
  ['Weak Encryption', 'java', 'weak_encryption'],
  ['Weak Encryption: Inadequate RSA Padding', 'java', 'weak_encryption_inadequate_rsa_padding'],
  ['Weak Encryption: Insufficient Key Size', 'java', 'weak_encryption_insufficient_key_size'],
  ['Weak SecurityManager Check: Overridable Method', 'java', 'weak_securitymanager_check_overridable_method'],
  ['Code Correctness: Call to sleep() in Lock', 'java', 'code_correctness_call_to_sleep_in_lock'],
  ['Code Correctness: Double-Checked Locking', 'java', 'code_correctness_double_checked_locking'],
  ['J2EE Bad Practices: Non-Serializable Object Stored in Session', 'java', 'j2ee_bad_practices_non_serializable_object_stored_in_session'],
  ['J2EE Bad Practices: System.exit', 'java', 'j2ee_badpractices_system_exit'],
  ['J2EE Bad Practices: Threads', 'java', 'j2ee_badpractices_threads'],
  ['Race Condition: Format Flaw', 'java', 'race_condition_format_flaw'],
  ['Race Condition: Singleton Member Field', 'java', 'singleton_member_field_race_condition'],
  ['Race Condition: Static Database Connection(dbconn)', 'java', 'race_dbconn'],
  ['Session Fixation', 'java', 'session_fixation']]

languages = rules.map { |rule| rule[1] }.uniq.sort
language_mapping = {'dotnet' => 'cs', 'python' => 'py', 'javascript' => 'js'}

puts "##############################################################"
puts "Generating XML files"
puts "##############################################################"
languages.each do |language|
  sonar_language=language_mapping[language]||language
  open("src/main/resources/org/sonar/plugins/fortify/base/rules-#{sonar_language}.xml", "w+") do |file|
    file.write('<rules>
        <!-- see names and descriptions in org/sonar/l10n/ -->
    ')
    rules.each do |rule|
      key = rule[2]
      name=rule[0]
      if rule[1]==language
        file.write("
          <rule>
            <key>#{key}</key><priority>MAJOR</priority><configKey>#{name}</configKey>
          </rule>
        ")
      end
    end
    file.write('</rules>')
  end
end

puts "##############################################################"
puts "Copy paste the following to org/sonar/l10n/fortify.properties. Be careful to keep fortify.* properties."
puts "##############################################################"

Net::HTTP.start("www.hpenterprisesecurity.com") do |http|
  rules.each do |rule|
    key = rule[2]
    language=rule[1]
    sonar_language=language_mapping[language]||language
    name=rule[0]
    puts "rule.fortify-#{sonar_language}.#{key}.name=#{name}"
    resp = http.get("/vulncat/en/vulncat/#{language}/#{key}.html")
    open("src/main/resources/org/sonar/l10n/fortify/rules/fortify-#{sonar_language}/#{key}.html", "w+") do |file|
      file.write(resp.body.gsub(/.*<\/h1>/m, '').gsub(/<div id="theFooter">.*/m, ''))
    end
  end
end

